/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Sell.UI;

import com.Sell.Helper.Auth;
import com.Sell.Helper.DesignHelper;
import com.Sell.Helper.FrameDragListener;
import com.Sell.Helper.ImageHelper;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author NguyenTruongChinh
 */
public class MainJFrame extends javax.swing.JFrame {
    
    private String[] imageList = {
        "slide0.jpg",
        "slide1.jpg",
        "slide2.jpg",
        "slide3.jpg",
        "slide4.jpg",
        "slide5.jpg",
        "slide6.jpg"
    };
    
    private int indexSlide = 0;

    /**
     * Creates new form MainJFrame
     */
    boolean click = false;

    public MainJFrame() {
        initComponents();
        init();
    }

    public void animationMenu() {
        if (click == false) {
            Thread th = new Thread() {
                @Override
                public void run() {
                    try {
                        for (int i = 0; i <= 240; i++) {
                            Thread.sleep(1);
                            panelMenu.setSize(i, panelMenu.getHeight());
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }
            };
            th.start();
            click = true;
        } //        else {
        //            Thread th = new Thread() {
        //                @Override
        //                public void run() {
        //                    try {
        //                        for (int i = 240; i >= 50; i--) {
        //                            Thread.sleep(1);
        //                            panelMenu.setSize(i, panelMenu.getHeight());
        //                        }
        //                    } catch (Exception e) {
        //                        JOptionPane.showMessageDialog(null, e);
        //                    }
        //                }
        //            };
        //            th.start();
        //            click = false;
        //        }
        else {
            panelMenu.setSize(50, panelMenu.getHeight());
            click = false;
        }
    }
    boolean click2 = false;

    public void displayUser() {
        if (click2 == false) {
            panelMenuAccount.setSize(1140, 60);
            click2 = true;
        } else {
            panelMenuAccount.setSize(0, 60);
            click2 = false;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFullForm = new javax.swing.JPanel();
        panelMenu = new com.k33ptoo.components.KGradientPanel();
        panelDieuKhienMenu = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        panelHomeItem = new javax.swing.JPanel();
        lblHomeText = new javax.swing.JLabel();
        lblHomeIcon = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        panelNhanVienItem = new javax.swing.JPanel();
        lblNhanVienText = new javax.swing.JLabel();
        lblNhanVienIcon = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        panelCuaHangItem = new javax.swing.JPanel();
        lblCuaHangText = new javax.swing.JLabel();
        lblCuaHangIcon = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        panelSanPhamItem = new javax.swing.JPanel();
        lblSanPhamText = new javax.swing.JLabel();
        lblSanPhamIcon = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        panelKhoItem = new javax.swing.JPanel();
        lblKhoText = new javax.swing.JLabel();
        lblKhoIcon = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        panelKhachHangItem = new javax.swing.JPanel();
        lblKhachHangText = new javax.swing.JLabel();
        lblKhachHangIcon = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        panelNhapHangItem = new javax.swing.JPanel();
        lblNhapHangIcon = new javax.swing.JLabel();
        lblNhapHangText = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        panelBanHangItem = new javax.swing.JPanel();
        lblBanHangIcon = new javax.swing.JLabel();
        lblBanHangText = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        panelDoanhThuItem = new javax.swing.JPanel();
        lblDoanhThuText = new javax.swing.JLabel();
        lblDoanhThuIcon = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblFullScreen = new javax.swing.JLabel();
        lblMiniMize = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        panelMenu2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelMenuAccount = new javax.swing.JPanel();
        lblDoiMatKhau = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        lblInfo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        lblSlide = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelFullForm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelFullForm.setLayout(new java.awt.BorderLayout());

        panelMenu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        panelMenu.setkBorderRadius(0);
        panelMenu.setkEndColor(new java.awt.Color(153, 153, 255));
        panelMenu.setkGradientFocus(250);
        panelMenu.setkStartColor(new java.awt.Color(102, 153, 255));
        panelMenu.setPreferredSize(new java.awt.Dimension(50, 650));

        panelDieuKhienMenu.setOpaque(false);
        panelDieuKhienMenu.setPreferredSize(new java.awt.Dimension(240, 50));
        panelDieuKhienMenu.setRequestFocusEnabled(false);

        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/menu.png"))); // NOI18N
        lblMenu.setPreferredSize(new java.awt.Dimension(50, 50));
        lblMenu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lblMenuFocusLost(evt);
            }
        });
        lblMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMenuMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelDieuKhienMenuLayout = new javax.swing.GroupLayout(panelDieuKhienMenu);
        panelDieuKhienMenu.setLayout(panelDieuKhienMenuLayout);
        panelDieuKhienMenuLayout.setHorizontalGroup(
            panelDieuKhienMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelDieuKhienMenuLayout.setVerticalGroup(
            panelDieuKhienMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelHomeItem.setBackground(new java.awt.Color(0, 153, 255));
        panelHomeItem.setPreferredSize(new java.awt.Dimension(240, 50));

        lblHomeText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHomeText.setForeground(new java.awt.Color(255, 255, 255));
        lblHomeText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblHomeText.setText("TRANG CHỦ");
        lblHomeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeTextMouseExited(evt);
            }
        });

        lblHomeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/home-icon.png"))); // NOI18N
        lblHomeIcon.setToolTipText("Trang chủ");
        lblHomeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHomeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelHomeItemLayout = new javax.swing.GroupLayout(panelHomeItem);
        panelHomeItem.setLayout(panelHomeItemLayout);
        panelHomeItemLayout.setHorizontalGroup(
            panelHomeItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeItemLayout.createSequentialGroup()
                .addComponent(lblHomeIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelHomeItemLayout.setVerticalGroup(
            panelHomeItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHomeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblHomeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel9.setOpaque(false);
        jPanel9.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelNhanVienItem.setBackground(new java.awt.Color(0, 153, 255));
        panelNhanVienItem.setPreferredSize(new java.awt.Dimension(240, 50));

        lblNhanVienText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNhanVienText.setForeground(new java.awt.Color(255, 255, 255));
        lblNhanVienText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNhanVienText.setText("QUẢN LÝ NHÂN VIÊN");
        lblNhanVienText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhanVienTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNhanVienTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNhanVienTextMouseExited(evt);
            }
        });

        lblNhanVienIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhanVienIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/users-icon.png"))); // NOI18N
        lblNhanVienIcon.setToolTipText("Quản lý Nhân viên");
        lblNhanVienIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNhanVienIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhanVienIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelNhanVienItemLayout = new javax.swing.GroupLayout(panelNhanVienItem);
        panelNhanVienItem.setLayout(panelNhanVienItemLayout);
        panelNhanVienItemLayout.setHorizontalGroup(
            panelNhanVienItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNhanVienItemLayout.createSequentialGroup()
                .addComponent(lblNhanVienIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNhanVienText, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelNhanVienItemLayout.setVerticalGroup(
            panelNhanVienItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNhanVienText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblNhanVienIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelCuaHangItem.setBackground(new java.awt.Color(0, 153, 255));
        panelCuaHangItem.setPreferredSize(new java.awt.Dimension(240, 50));

        lblCuaHangText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCuaHangText.setForeground(new java.awt.Color(255, 255, 255));
        lblCuaHangText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCuaHangText.setText("QUẢN LÝ CỬA HÀNG");
        lblCuaHangText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCuaHangTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCuaHangTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCuaHangTextMouseExited(evt);
            }
        });

        lblCuaHangIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCuaHangIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/Shop-icon.png"))); // NOI18N
        lblCuaHangIcon.setToolTipText("Quản lý Cửa hàng");
        lblCuaHangIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCuaHangIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCuaHangIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCuaHangItemLayout = new javax.swing.GroupLayout(panelCuaHangItem);
        panelCuaHangItem.setLayout(panelCuaHangItemLayout);
        panelCuaHangItemLayout.setHorizontalGroup(
            panelCuaHangItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuaHangItemLayout.createSequentialGroup()
                .addComponent(lblCuaHangIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCuaHangText, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelCuaHangItemLayout.setVerticalGroup(
            panelCuaHangItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCuaHangText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblCuaHangIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelSanPhamItem.setBackground(new java.awt.Color(0, 153, 255));
        panelSanPhamItem.setPreferredSize(new java.awt.Dimension(240, 50));

        lblSanPhamText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSanPhamText.setForeground(new java.awt.Color(255, 255, 255));
        lblSanPhamText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSanPhamText.setText("QUẢN LÝ SẢN PHẨM");
        lblSanPhamText.setPreferredSize(new java.awt.Dimension(76, 76));
        lblSanPhamText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSanPhamTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSanPhamTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSanPhamTextMouseExited(evt);
            }
        });

        lblSanPhamIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSanPhamIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/clothes-icon.png"))); // NOI18N
        lblSanPhamIcon.setToolTipText("Quản lý Sản phẩm");
        lblSanPhamIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSanPhamIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSanPhamIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSanPhamItemLayout = new javax.swing.GroupLayout(panelSanPhamItem);
        panelSanPhamItem.setLayout(panelSanPhamItemLayout);
        panelSanPhamItemLayout.setHorizontalGroup(
            panelSanPhamItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSanPhamItemLayout.createSequentialGroup()
                .addComponent(lblSanPhamIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSanPhamText, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSanPhamItemLayout.setVerticalGroup(
            panelSanPhamItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSanPhamText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lblSanPhamIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel14.setOpaque(false);
        jPanel14.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelKhoItem.setBackground(new java.awt.Color(0, 153, 255));
        panelKhoItem.setPreferredSize(new java.awt.Dimension(240, 50));

        lblKhoText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblKhoText.setForeground(new java.awt.Color(255, 255, 255));
        lblKhoText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKhoText.setText("QUẢN LÝ LOẠI HÀNG");
        lblKhoText.setPreferredSize(new java.awt.Dimension(76, 76));
        lblKhoText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhoTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKhoTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKhoTextMouseExited(evt);
            }
        });

        lblKhoIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/type-icon.png"))); // NOI18N
        lblKhoIcon.setToolTipText("Quản lý Loại hàng");
        lblKhoIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKhoIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhoIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelKhoItemLayout = new javax.swing.GroupLayout(panelKhoItem);
        panelKhoItem.setLayout(panelKhoItemLayout);
        panelKhoItemLayout.setHorizontalGroup(
            panelKhoItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKhoItemLayout.createSequentialGroup()
                .addComponent(lblKhoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKhoText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelKhoItemLayout.setVerticalGroup(
            panelKhoItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKhoText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lblKhoIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel16.setOpaque(false);
        jPanel16.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelKhachHangItem.setBackground(new java.awt.Color(0, 153, 255));
        panelKhachHangItem.setPreferredSize(new java.awt.Dimension(240, 50));

        lblKhachHangText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblKhachHangText.setForeground(new java.awt.Color(255, 255, 255));
        lblKhachHangText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblKhachHangText.setText("QUẢN LÝ KHÁCH HÀNG");
        lblKhachHangText.setPreferredSize(new java.awt.Dimension(76, 76));
        lblKhachHangText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhachHangTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKhachHangTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKhachHangTextMouseExited(evt);
            }
        });

        lblKhachHangIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKhachHangIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/customer-icon.png"))); // NOI18N
        lblKhachHangIcon.setToolTipText("Quản lý Khách hàng");
        lblKhachHangIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKhachHangIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKhachHangIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelKhachHangItemLayout = new javax.swing.GroupLayout(panelKhachHangItem);
        panelKhachHangItem.setLayout(panelKhachHangItemLayout);
        panelKhachHangItemLayout.setHorizontalGroup(
            panelKhachHangItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKhachHangItemLayout.createSequentialGroup()
                .addComponent(lblKhachHangIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKhachHangText, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelKhachHangItemLayout.setVerticalGroup(
            panelKhachHangItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKhachHangText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lblKhachHangIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel8.setOpaque(false);
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelNhapHangItem.setBackground(new java.awt.Color(0, 153, 255));
        panelNhapHangItem.setPreferredSize(new java.awt.Dimension(240, 50));

        lblNhapHangIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNhapHangIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/order-icon.png"))); // NOI18N
        lblNhapHangIcon.setToolTipText("Quản lý Hoá đơn nhập hàng");
        lblNhapHangIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNhapHangIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhapHangIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNhapHangIconMouseEntered(evt);
            }
        });

        lblNhapHangText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNhapHangText.setForeground(new java.awt.Color(255, 255, 255));
        lblNhapHangText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNhapHangText.setText("QUẢN LÝ NHẬP HÀNG");
        lblNhapHangText.setPreferredSize(new java.awt.Dimension(76, 76));
        lblNhapHangText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNhapHangTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNhapHangTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNhapHangTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelNhapHangItemLayout = new javax.swing.GroupLayout(panelNhapHangItem);
        panelNhapHangItem.setLayout(panelNhapHangItemLayout);
        panelNhapHangItemLayout.setHorizontalGroup(
            panelNhapHangItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNhapHangItemLayout.createSequentialGroup()
                .addComponent(lblNhapHangIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNhapHangText, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelNhapHangItemLayout.setVerticalGroup(
            panelNhapHangItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNhapHangIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lblNhapHangText, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel11.setOpaque(false);
        jPanel11.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelBanHangItem.setBackground(new java.awt.Color(0, 153, 255));
        panelBanHangItem.setPreferredSize(new java.awt.Dimension(240, 50));

        lblBanHangIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanHangIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/sell.png"))); // NOI18N
        lblBanHangIcon.setToolTipText("Quản lý Hoá đơn bán hàng");
        lblBanHangIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBanHangIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHangIconMouseClicked(evt);
            }
        });

        lblBanHangText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBanHangText.setForeground(new java.awt.Color(255, 255, 255));
        lblBanHangText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBanHangText.setText("QUẢN LÝ BÁN HÀNG");
        lblBanHangText.setPreferredSize(new java.awt.Dimension(76, 76));
        lblBanHangText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBanHangTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBanHangTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBanHangTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelBanHangItemLayout = new javax.swing.GroupLayout(panelBanHangItem);
        panelBanHangItem.setLayout(panelBanHangItemLayout);
        panelBanHangItemLayout.setHorizontalGroup(
            panelBanHangItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBanHangItemLayout.createSequentialGroup()
                .addComponent(lblBanHangIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBanHangText, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelBanHangItemLayout.setVerticalGroup(
            panelBanHangItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBanHangIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(lblBanHangText, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel18.setOpaque(false);
        jPanel18.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        panelDoanhThuItem.setBackground(new java.awt.Color(0, 153, 255));
        panelDoanhThuItem.setPreferredSize(new java.awt.Dimension(240, 50));

        lblDoanhThuText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDoanhThuText.setForeground(new java.awt.Color(255, 255, 255));
        lblDoanhThuText.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDoanhThuText.setText("XEM DOANH THU");
        lblDoanhThuText.setPreferredSize(new java.awt.Dimension(76, 76));
        lblDoanhThuText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoanhThuTextMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDoanhThuTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDoanhThuTextMouseExited(evt);
            }
        });

        lblDoanhThuIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoanhThuIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/money-icon.png"))); // NOI18N
        lblDoanhThuIcon.setToolTipText("Quản lý Doanh thu");
        lblDoanhThuIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDoanhThuIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoanhThuIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDoanhThuIconMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelDoanhThuItemLayout = new javax.swing.GroupLayout(panelDoanhThuItem);
        panelDoanhThuItem.setLayout(panelDoanhThuItemLayout);
        panelDoanhThuItemLayout.setHorizontalGroup(
            panelDoanhThuItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDoanhThuItemLayout.createSequentialGroup()
                .addComponent(lblDoanhThuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDoanhThuText, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelDoanhThuItemLayout.setVerticalGroup(
            panelDoanhThuItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDoanhThuText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lblDoanhThuIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel23.setOpaque(false);
        jPanel23.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDieuKhienMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelHomeItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelNhanVienItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelCuaHangItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSanPhamItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelKhoItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelKhachHangItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelNhapHangItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBanHangItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelDoanhThuItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panelDieuKhienMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelHomeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelNhanVienItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelCuaHangItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelSanPhamItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelKhoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelKhachHangItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelNhapHangItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelBanHangItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(panelDoanhThuItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelFullForm.add(panelMenu, java.awt.BorderLayout.WEST);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(58, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 118));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/brandname-icon.png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jLabel6.setPreferredSize(new java.awt.Dimension(126, 50));

        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/exit-start-icon.png"))); // NOI18N
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.setPreferredSize(new java.awt.Dimension(50, 50));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });

        lblFullScreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFullScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/fullscreen-icon.png"))); // NOI18N
        lblFullScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFullScreen.setPreferredSize(new java.awt.Dimension(50, 50));
        lblFullScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFullScreenMouseClicked(evt);
            }
        });

        lblMiniMize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMiniMize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/minimize-icon.jpg"))); // NOI18N
        lblMiniMize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMiniMize.setPreferredSize(new java.awt.Dimension(50, 50));
        lblMiniMize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMiniMizeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 856, Short.MAX_VALUE)
                .addComponent(lblMiniMize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFullScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFullScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMiniMize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        panelFullForm.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1200, 722));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setMinimumSize(new java.awt.Dimension(100, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(1008, 60));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel20.setPreferredSize(new java.awt.Dimension(100, 65));
        jPanel20.setLayout(new java.awt.BorderLayout());

        panelMenu2.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu2.setMinimumSize(new java.awt.Dimension(200, 79));
        panelMenu2.setPreferredSize(new java.awt.Dimension(420, 65));

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(418, 60));
        jPanel1.setLayout(new java.awt.BorderLayout());

        panelMenuAccount.setOpaque(false);
        panelMenuAccount.setPreferredSize(new java.awt.Dimension(1140, 60));

        lblDoiMatKhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDoiMatKhau.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/changepass-icon.png"))); // NOI18N
        lblDoiMatKhau.setText("   ĐỔI MẬT KHẨU");
        lblDoiMatKhau.setPreferredSize(new java.awt.Dimension(200, 30));
        lblDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoiMatKhauMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDoiMatKhauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDoiMatKhauMouseExited(evt);
            }
        });

        lblDangXuat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/logout-icon.png"))); // NOI18N
        lblDangXuat.setText("   ĐĂNG XUẤT");
        lblDangXuat.setPreferredSize(new java.awt.Dimension(200, 30));
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseExited(evt);
            }
        });

        lblInfo.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N

        javax.swing.GroupLayout panelMenuAccountLayout = new javax.swing.GroupLayout(panelMenuAccount);
        panelMenuAccount.setLayout(panelMenuAccountLayout);
        panelMenuAccountLayout.setHorizontalGroup(
            panelMenuAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuAccountLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addGap(253, 253, 253)
                .addComponent(lblDoiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelMenuAccountLayout.setVerticalGroup(
            panelMenuAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuAccountLayout.createSequentialGroup()
                .addGroup(panelMenuAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblDangXuat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(lblDoiMatKhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        jPanel1.add(panelMenuAccount, java.awt.BorderLayout.LINE_END);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/Users-Administrator-icon.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel17.setPreferredSize(new java.awt.Dimension(60, 60));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMenu2Layout = new javax.swing.GroupLayout(panelMenu2);
        panelMenu2.setLayout(panelMenu2Layout);
        panelMenu2Layout.setHorizontalGroup(
            panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1123, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMenu2Layout.setVerticalGroup(
            panelMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel20.add(panelMenu2, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        panelMain.setBackground(new java.awt.Color(255, 255, 255));
        panelMain.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        panelMain.setMinimumSize(new java.awt.Dimension(1010, 619));
        panelMain.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                panelMainFocusGained(evt);
            }
        });
        panelMain.setLayout(new java.awt.BorderLayout());

        lblSlide.setBackground(new java.awt.Color(51, 255, 51));
        panelMain.add(lblSlide, java.awt.BorderLayout.CENTER);
        lblSlide.getAccessibleContext().setAccessibleParent(this);

        jPanel4.add(panelMain, java.awt.BorderLayout.CENTER);

        panelFullForm.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFullForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFullForm, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseClicked

        animationMenu();
    }//GEN-LAST:event_lblMenuMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked

        System.exit(0);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblFullScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFullScreenMouseClicked

        if (this.getExtendedState() != MainJFrame.MAXIMIZED_BOTH) {
            this.setExtendedState(MainJFrame.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(MainJFrame.NORMAL);
        }
    }//GEN-LAST:event_lblFullScreenMouseClicked

    private void lblNhanVienTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienTextMouseEntered

        DesignHelper.hoverMenuEnter(lblNhanVienText, panelNhanVienItem);
    }//GEN-LAST:event_lblNhanVienTextMouseEntered

    private void lblNhanVienTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienTextMouseExited

        DesignHelper.hoverMenuExit(lblNhanVienText, panelNhanVienItem);
    }//GEN-LAST:event_lblNhanVienTextMouseExited

    private void lblCuaHangTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCuaHangTextMouseEntered

        DesignHelper.hoverMenuEnter(lblCuaHangText, panelCuaHangItem);
    }//GEN-LAST:event_lblCuaHangTextMouseEntered

    private void lblCuaHangTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCuaHangTextMouseExited

        DesignHelper.hoverMenuExit(lblCuaHangText, panelCuaHangItem);
    }//GEN-LAST:event_lblCuaHangTextMouseExited

    private void lblMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuMouseEntered

        DesignHelper.hoverMenuEnter(lblMenu, panelDieuKhienMenu);
    }//GEN-LAST:event_lblMenuMouseEntered

    private void lblSanPhamTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSanPhamTextMouseEntered

        DesignHelper.hoverMenuEnter(lblSanPhamText, panelSanPhamItem);
    }//GEN-LAST:event_lblSanPhamTextMouseEntered

    private void lblSanPhamTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSanPhamTextMouseExited

        DesignHelper.hoverMenuExit(lblSanPhamText, panelSanPhamItem);
    }//GEN-LAST:event_lblSanPhamTextMouseExited

    private void lblKhoTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhoTextMouseEntered

        DesignHelper.hoverMenuEnter(lblKhoText, panelKhoItem);
    }//GEN-LAST:event_lblKhoTextMouseEntered

    private void lblKhoTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhoTextMouseExited

        DesignHelper.hoverMenuExit(lblKhoText, panelKhoItem);
    }//GEN-LAST:event_lblKhoTextMouseExited

    private void lblKhachHangTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangTextMouseEntered

        DesignHelper.hoverMenuEnter(lblKhachHangText, panelKhachHangItem);
    }//GEN-LAST:event_lblKhachHangTextMouseEntered

    private void lblKhachHangTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangTextMouseExited

        DesignHelper.hoverMenuExit(lblKhachHangText, panelKhachHangItem);
    }//GEN-LAST:event_lblKhachHangTextMouseExited

    private void lblNhapHangTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapHangTextMouseEntered

        DesignHelper.hoverMenuEnter(lblNhapHangText, panelNhapHangItem);
    }//GEN-LAST:event_lblNhapHangTextMouseEntered

    private void lblNhapHangTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapHangTextMouseExited

        DesignHelper.hoverMenuExit(lblNhapHangText, panelNhapHangItem);
    }//GEN-LAST:event_lblNhapHangTextMouseExited

    private void lblDoanhThuTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuTextMouseEntered

        DesignHelper.hoverMenuEnter(lblDoanhThuText, panelDoanhThuItem);
    }//GEN-LAST:event_lblDoanhThuTextMouseEntered

    private void lblDoanhThuTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuTextMouseExited

        DesignHelper.hoverMenuExit(lblDoanhThuText, panelDoanhThuItem);
    }//GEN-LAST:event_lblDoanhThuTextMouseExited

    private void lblMiniMizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMiniMizeMouseClicked

        this.setState(MainJFrame.ICONIFIED);
    }//GEN-LAST:event_lblMiniMizeMouseClicked
    private JPanel childPanel;
    private void lblNhanVienIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienIconMouseClicked

        showPanel(new QL_NhanVien());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblNhanVienIconMouseClicked

    private void lblNhanVienTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhanVienTextMouseClicked

        showPanel(new QL_NhanVien());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblNhanVienTextMouseClicked

    private void lblHomeTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeTextMouseClicked

        showPanel(new HomeJPanel());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblHomeTextMouseClicked

    private void lblHomeTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeTextMouseEntered

        DesignHelper.hoverMenuEnter(lblHomeText, panelHomeItem);
    }//GEN-LAST:event_lblHomeTextMouseEntered

    private void lblHomeTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeTextMouseExited

        DesignHelper.hoverMenuExit(lblHomeText, panelHomeItem);
    }//GEN-LAST:event_lblHomeTextMouseExited

    private void lblHomeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeIconMouseClicked
        
//        showPanel(new SlideShowJPanel());
        click = true;
        animationMenu();
        initSlideShow();
    }//GEN-LAST:event_lblHomeIconMouseClicked

    private void lblMenuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lblMenuFocusLost

    }//GEN-LAST:event_lblMenuFocusLost

    private void lblCuaHangTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCuaHangTextMouseClicked
        showPanel(new QL_CuaHang());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblCuaHangTextMouseClicked

    private void lblCuaHangIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCuaHangIconMouseClicked
        showPanel(new QL_CuaHang());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblCuaHangIconMouseClicked

    private void lblKhachHangIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangIconMouseClicked
        showPanel(new QL_KhachHang());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblKhachHangIconMouseClicked

    private void lblSanPhamIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSanPhamIconMouseClicked
        showPanel(new QL_SanPham());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblSanPhamIconMouseClicked

    private void lblNhapHangIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapHangIconMouseClicked

        showPanel(new QL_HoaDonNhap());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblNhapHangIconMouseClicked

    private void lblDoanhThuIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuIconMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDoanhThuIconMouseEntered

    private void lblDoanhThuIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuIconMouseClicked
        // TODO add your handling code here:
        showPanel(new ThongKeJPanel());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblDoanhThuIconMouseClicked

    private void lblBanHangIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHangIconMouseClicked
        // TODO add your handling code here:
        showPanel(new QL_HoaDonBanHang());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblBanHangIconMouseClicked

    private void lblBanHangTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHangTextMouseEntered
        // TODO add your handling code here:
        DesignHelper.hoverMenuEnter(lblBanHangText, panelBanHangItem);
    }//GEN-LAST:event_lblBanHangTextMouseEntered

    private void lblBanHangTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHangTextMouseExited
        // TODO add your handling code here:
        DesignHelper.hoverMenuExit(lblBanHangText, panelBanHangItem);
    }//GEN-LAST:event_lblBanHangTextMouseExited

    private void lblKhoIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhoIconMouseClicked
        // TODO add your handling code here:
        showPanel(new QL_LoaiHang());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblKhoIconMouseClicked

    private void lblNhapHangIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapHangIconMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblNhapHangIconMouseEntered

    private void lblBanHangTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBanHangTextMouseClicked
        // TODO add your handling code here:
        showPanel(new QL_HoaDonBanHang());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblBanHangTextMouseClicked

    private void lblNhapHangTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNhapHangTextMouseClicked
        // TODO add your handling code here:
        showPanel(new QL_HoaDonNhap());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblNhapHangTextMouseClicked

    private void lblKhachHangTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhachHangTextMouseClicked
        // TODO add your handling code here:
        showPanel(new QL_KhachHang());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblKhachHangTextMouseClicked

    private void lblSanPhamTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSanPhamTextMouseClicked
        // TODO add your handling code here:
        showPanel(new QL_SanPham());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblSanPhamTextMouseClicked

    private void lblKhoTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKhoTextMouseClicked
        // TODO add your handling code here:
        showPanel(new QL_LoaiHang());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblKhoTextMouseClicked

    private void lblDoanhThuTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoanhThuTextMouseClicked
        // TODO add your handling code here:
        showPanel(new ThongKeJPanel());
        click = true;
        animationMenu();
    }//GEN-LAST:event_lblDoanhThuTextMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked

        displayUser();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void lblDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseExited
        // TODO add your handling code here:
        lblDangXuat.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblDangXuatMouseExited

    private void lblDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseEntered
        // TODO add your handling code here:
        lblDangXuat.setForeground(new Color(255, 76, 48));
        lblDangXuat.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblDangXuatMouseEntered

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new DangNhapJFrame().setVisible(true);
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void lblDoiMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMatKhauMouseExited
        // TODO add your handling code here:
        lblDoiMatKhau.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblDoiMatKhauMouseExited

    private void lblDoiMatKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMatKhauMouseEntered
        // TODO add your handling code here:
        lblDoiMatKhau.setForeground(new Color(255, 76, 48));
        lblDoiMatKhau.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblDoiMatKhauMouseEntered

    private void lblDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMatKhauMouseClicked
        // TODO add your handling code here:
        new DoiMatKhauJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_lblDoiMatKhauMouseClicked

    private void panelMainFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_panelMainFocusGained

    }//GEN-LAST:event_panelMainFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> {
            new FrameDragListener(new MainJFrame());
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblBanHangIcon;
    private javax.swing.JLabel lblBanHangText;
    private javax.swing.JLabel lblCuaHangIcon;
    private javax.swing.JLabel lblCuaHangText;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblDoanhThuIcon;
    private javax.swing.JLabel lblDoanhThuText;
    private javax.swing.JLabel lblDoiMatKhau;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFullScreen;
    private javax.swing.JLabel lblHomeIcon;
    private javax.swing.JLabel lblHomeText;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblKhachHangIcon;
    private javax.swing.JLabel lblKhachHangText;
    private javax.swing.JLabel lblKhoIcon;
    private javax.swing.JLabel lblKhoText;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblMiniMize;
    private javax.swing.JLabel lblNhanVienIcon;
    private javax.swing.JLabel lblNhanVienText;
    private javax.swing.JLabel lblNhapHangIcon;
    private javax.swing.JLabel lblNhapHangText;
    private javax.swing.JLabel lblSanPhamIcon;
    private javax.swing.JLabel lblSanPhamText;
    private javax.swing.JLabel lblSlide;
    private javax.swing.JPanel panelBanHangItem;
    private javax.swing.JPanel panelCuaHangItem;
    private javax.swing.JPanel panelDieuKhienMenu;
    private javax.swing.JPanel panelDoanhThuItem;
    private javax.swing.JPanel panelFullForm;
    private javax.swing.JPanel panelHomeItem;
    private javax.swing.JPanel panelKhachHangItem;
    private javax.swing.JPanel panelKhoItem;
    private javax.swing.JPanel panelMain;
    private com.k33ptoo.components.KGradientPanel panelMenu;
    private javax.swing.JPanel panelMenu2;
    private javax.swing.JPanel panelMenuAccount;
    private javax.swing.JPanel panelNhanVienItem;
    private javax.swing.JPanel panelNhapHangItem;
    private javax.swing.JPanel panelSanPhamItem;
    // End of variables declaration//GEN-END:variables

    private void init() {
        this.setLocationRelativeTo(null);
        click = true;
        animationMenu();
//        showPanel(new Test());
        this.hello();
        initSlideShow();
    }
    
//    public void showPanel(JPanel panel) {
//        panelMain.removeAll();
//        panelMain.add(panel);
//        panelMain.validate();
////        lblSlide.setVisible(false);
//    }
    
    public void showPanel(JPanel panel) {
        try {                        
            for (int i = 1; i < panelMain.getComponentCount(); i++) {
                panelMain.remove(1);
            }
        } catch (ArrayIndexOutOfBoundsException e) {
        }
        panelMain.removeAll();
        panelMain.add(panel);
        panelMain.validate();
        lblSlide.setVisible(false);
    }
    
    private void initSlideShow() {
        setBackGround(imageList[0]);
        indexSlide++;
        startSlideShow();
        lblSlide.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                setBackGround(imageList[indexSlide]);
            }
        });
        lblSlide.setVisible(true);
    }

    private void setBackGround(String fileName) {
        lblSlide.setIcon(ImageHelper.readAndResize(panelMain, fileName));
    }

    private void startSlideShow() {
        new Timer(2000, (ActionEvent e) -> {
            setBackGround(imageList[indexSlide]);
            indexSlide++;
            if (indexSlide == imageList.length) {
                indexSlide = 0;
            }
        }).start();
    }
    
    private void hello(){
        String vaiTro;
        switch (Auth.user.getVaiTro()) {
            case 1:
                vaiTro = "Nhân Viên";
                break;
            case 2:
                vaiTro = "Quản Lý";
                break;
            case 3:
                vaiTro = "Giám Đốc";
                break;
            default:
                vaiTro = "Đã Nghỉ Việc";
                break;
        }
        lblInfo.setText(Auth.user.getMaNV().trim() + " - " + Auth.user.getHoTen() + " - " + vaiTro);
    }

    // bị lỗi conflict với thread ở Menu con
//    private void clock() {
//        SimpleDateFormat fmt = new SimpleDateFormat("hh:mm:ss a");
//        Timer timer1 = new Timer(1000, (ActionEvent e) -> {
//            lblDongHo.setText(fmt.format(new Date()));
//        });
//        timer1.start();
//    }
}
