
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Sell.UI;

import com.Sell.DAO.ChiTietCuaHangDAO;
import com.Sell.DAO.CuaHangDAO;
import com.Sell.Helper.DesignHelper;
import com.Sell.Helper.MsgBox;
import com.Sell.entity.ChiTietCuaHang;
import com.Sell.entity.CuaHang;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NguyenTruongChinh
 */
public class QL_CuaHang extends javax.swing.JPanel {

    private CuaHangDAO dao = new CuaHangDAO();
    private int row = -1;

    /**
     * Creates new form CuaHangJPanel
     */
    public QL_CuaHang() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitle = new com.k33ptoo.components.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        panelCuaHang = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        panelInput = new javax.swing.JPanel();
        txtMaCuaHang = new javax.swing.JTextField();
        txtMaQuanLy = new javax.swing.JTextField();
        cboTrangThai = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        panelFunction = new javax.swing.JPanel();
        btnMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        panelDieuKhien = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtTimKiemCuaHang = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListCuaHang = new javax.swing.JTable();
        panelChiTiet = new javax.swing.JPanel();
        panelSearch = new javax.swing.JPanel();
        cboCuaHang = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiemChiTiet = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        btnThongTin = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblListCuaHangChiTiet = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1010, 619));
        setLayout(new java.awt.BorderLayout());

        panelTitle.setkBorderRadius(0);
        panelTitle.setkEndColor(new java.awt.Color(102, 216, 211));
        panelTitle.setkGradientFocus(1000);
        panelTitle.setkStartColor(new java.awt.Color(0, 185, 215));
        panelTitle.setPreferredSize(new java.awt.Dimension(1150, 50));
        panelTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTitleMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TRANG CHỦ/ QUẢN LÝ CỬA HÀNG");
        jLabel6.setPreferredSize(new java.awt.Dimension(210, 50));

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(770, Short.MAX_VALUE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(panelTitle, java.awt.BorderLayout.NORTH);

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setPreferredSize(new java.awt.Dimension(1010, 540));
        panelContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTitleMouseClicked(evt);
            }
        });
        panelContent.setLayout(new java.awt.CardLayout());

        panelCuaHang.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(335, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ CỬA HÀNG");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTitleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelCuaHang.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTitleMouseClicked(evt);
            }
        });

        jPanel6.setPreferredSize(new java.awt.Dimension(1000, 499));

        jPanel7.setPreferredSize(new java.awt.Dimension(1000, 475));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTitleMouseClicked(evt);
            }
        });

        txtMaCuaHang.setPreferredSize(new java.awt.Dimension(80, 35));
        txtMaCuaHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaCuaHangFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaCuaHangFocusLost(evt);
            }
        });

        txtMaQuanLy.setPreferredSize(new java.awt.Dimension(80, 35));
        txtMaQuanLy.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaQuanLyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaQuanLyFocusLost(evt);
            }
        });

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trạng thái", "Còn hoạt động", "Ngừng hoạt động" }));

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        txtDiaChi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiaChiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDiaChiFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txtDiaChi);

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaCuaHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaQuanLy, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(cboTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMaCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMaQuanLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMoi.setBackground(new java.awt.Color(51, 255, 255));
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/refresh-icon.png"))); // NOI18N
        btnMoi.setText(" MỚI");
        btnMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMoi.setPreferredSize(new java.awt.Dimension(150, 40));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(51, 255, 0));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/Add.png"))); // NOI18N
        btnThem.setText(" THÊM");
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.setPreferredSize(new java.awt.Dimension(150, 40));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 0, 0));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/Delete.png"))); // NOI18N
        btnXoa.setText(" XÓA");
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.setPreferredSize(new java.awt.Dimension(150, 40));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 255, 0));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/UPDATE.png"))); // NOI18N
        btnSua.setText(" SỬA");
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.setPreferredSize(new java.awt.Dimension(150, 40));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFunctionLayout = new javax.swing.GroupLayout(panelFunction);
        panelFunction.setLayout(panelFunctionLayout);
        panelFunctionLayout.setHorizontalGroup(
            panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFunctionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFunctionLayout.createSequentialGroup()
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFunctionLayout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFunctionLayout.setVerticalGroup(
            panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFunctionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFirst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFirst.setText("|<");
        btnFirst.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFirst.setPreferredSize(new java.awt.Dimension(100, 40));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrev.setText("<<");
        btnPrev.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrev.setPreferredSize(new java.awt.Dimension(100, 40));
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext.setText(">>");
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.setPreferredSize(new java.awt.Dimension(100, 40));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLast.setText(">|");
        btnLast.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLast.setPreferredSize(new java.awt.Dimension(100, 40));
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("CHI TIẾT CỬA HÀNG");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtTimKiemCuaHang.setPreferredSize(new java.awt.Dimension(69, 35));
        txtTimKiemCuaHang.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemCuaHangCaretUpdate(evt);
            }
        });
        txtTimKiemCuaHang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemCuaHangFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemCuaHangFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panelDieuKhienLayout = new javax.swing.GroupLayout(panelDieuKhien);
        panelDieuKhien.setLayout(panelDieuKhienLayout);
        panelDieuKhienLayout.setHorizontalGroup(
            panelDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDieuKhienLayout.createSequentialGroup()
                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(txtTimKiemCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelDieuKhienLayout.setVerticalGroup(
            panelDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelDieuKhienLayout.createSequentialGroup()
                .addComponent(txtTimKiemCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tblListCuaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListCuaHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListCuaHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblListCuaHang);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFunction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDieuKhien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDieuKhien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        panelCuaHang.add(jPanel4, java.awt.BorderLayout.CENTER);

        panelContent.add(panelCuaHang, "card2");

        panelChiTiet.setLayout(new java.awt.BorderLayout());

        panelSearch.setBackground(new java.awt.Color(255, 255, 255));

        cboCuaHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCuaHang.setPreferredSize(new java.awt.Dimension(300, 30));
        cboCuaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCuaHangActionPerformed(evt);
            }
        });
        panelSearch.add(cboCuaHang);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(120, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelSearch.add(jPanel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TÌM KIẾM SP");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 40));
        panelSearch.add(jLabel2);

        txtTimKiemChiTiet.setPreferredSize(new java.awt.Dimension(400, 30));
        txtTimKiemChiTiet.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemChiTietCaretUpdate(evt);
            }
        });
        txtTimKiemChiTiet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemChiTietFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemChiTietFocusLost(evt);
            }
        });
        panelSearch.add(txtTimKiemChiTiet);

        panelChiTiet.add(panelSearch, java.awt.BorderLayout.PAGE_START);

        jPanel11.setPreferredSize(new java.awt.Dimension(1010, 50));

        btnThongTin.setBackground(new java.awt.Color(255, 153, 0));
        btnThongTin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThongTin.setText("THÔNG TIN CỬA HÀNG");
        btnThongTin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongTinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(770, Short.MAX_VALUE)
                .addComponent(btnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(btnThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelChiTiet.add(jPanel11, java.awt.BorderLayout.PAGE_END);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);

        tblListCuaHangChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Cửa hàng", "Mã Sản Phẩm", "Số lượng"
            }
        ));
        tblListCuaHangChiTiet.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(tblListCuaHangChiTiet);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelChiTiet.add(jPanel12, java.awt.BorderLayout.CENTER);

        panelContent.add(panelChiTiet, "card3");

        add(panelContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelChiTiet.setVisible(true);
        panelCuaHang.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongTinActionPerformed
        panelCuaHang.setVisible(true);
        panelChiTiet.setVisible(false);
    }//GEN-LAST:event_btnThongTinActionPerformed

    private void txtMaCuaHangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaCuaHangFocusGained
        if (txtMaCuaHang.getText().equals("Mã cửa hàng")) {
            txtMaCuaHang.setText("");
            DesignHelper.deletePlaceHolderTextField(txtMaCuaHang);
        }
    }//GEN-LAST:event_txtMaCuaHangFocusGained

    private void txtMaCuaHangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaCuaHangFocusLost
        if (txtMaCuaHang.getText().trim().length() == 0) {
            txtMaCuaHang.setText("Mã cửa hàng");
            DesignHelper.addPlaceHolderTextField(txtMaCuaHang);
        }
    }//GEN-LAST:event_txtMaCuaHangFocusLost

    private void txtMaQuanLyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaQuanLyFocusGained
        if (txtMaQuanLy.getText().equals("Mã quản lý")) {
            txtMaQuanLy.setText("");
            DesignHelper.deletePlaceHolderTextField(txtMaQuanLy);
        }
    }//GEN-LAST:event_txtMaQuanLyFocusGained

    private void txtMaQuanLyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaQuanLyFocusLost
        if (txtMaQuanLy.getText().trim().length() == 0) {
            txtMaQuanLy.setText("Mã quản lý");
            DesignHelper.addPlaceHolderTextField(txtMaQuanLy);
        }
    }//GEN-LAST:event_txtMaQuanLyFocusLost

    private void txtDiaChiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaChiFocusGained
        if (txtDiaChi.getText().equals("Địa chỉ")) {
            txtDiaChi.setText("");
            DesignHelper.deletePlaceHolderTextField(txtDiaChi);
        }
    }//GEN-LAST:event_txtDiaChiFocusGained

    private void txtDiaChiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiaChiFocusLost
        if (txtDiaChi.getText().trim().length() == 0) {
            txtDiaChi.setText("Địa chỉ");
            DesignHelper.addPlaceHolderTextField(txtDiaChi);
        }
    }//GEN-LAST:event_txtDiaChiFocusLost

    private void txtTimKiemCuaHangFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemCuaHangFocusGained

    }//GEN-LAST:event_txtTimKiemCuaHangFocusGained

    private void txtTimKiemCuaHangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemCuaHangFocusLost

    }//GEN-LAST:event_txtTimKiemCuaHangFocusLost

    private void txtTimKiemChiTietFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemChiTietFocusGained

    }//GEN-LAST:event_txtTimKiemChiTietFocusGained

    private void txtTimKiemChiTietFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemChiTietFocusLost

    }//GEN-LAST:event_txtTimKiemChiTietFocusLost

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblListCuaHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListCuaHangMouseClicked

        if (evt.getClickCount() == 2) {
            this.row = tblListCuaHang.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblListCuaHangMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        this.next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void panelTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTitleMouseClicked
        JComponent component = (JComponent) evt.getSource();
        component.requestFocus();
    }//GEN-LAST:event_panelTitleMouseClicked

    private void cboCuaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCuaHangActionPerformed
        fillToTableChiTietCuaHang();
    }//GEN-LAST:event_cboCuaHangActionPerformed

    private void txtTimKiemChiTietCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemChiTietCaretUpdate
        fillToTableChiTietCuaHang();
    }//GEN-LAST:event_txtTimKiemChiTietCaretUpdate

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        this.first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        this.prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        this.last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void txtTimKiemCuaHangCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemCuaHangCaretUpdate
        this.find();
    }//GEN-LAST:event_txtTimKiemCuaHangCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThongTin;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboCuaHang;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelChiTiet;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelCuaHang;
    private javax.swing.JPanel panelDieuKhien;
    private javax.swing.JPanel panelFunction;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelSearch;
    private com.k33ptoo.components.KGradientPanel panelTitle;
    private javax.swing.JTable tblListCuaHang;
    private javax.swing.JTable tblListCuaHangChiTiet;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtMaCuaHang;
    private javax.swing.JTextField txtMaQuanLy;
    private javax.swing.JTextField txtTimKiemChiTiet;
    private javax.swing.JTextField txtTimKiemCuaHang;
    // End of variables declaration//GEN-END:variables

    private void init() {
        setTable();
        fillTable();
        fillComboBoxCuaHang();
        fillToTableChiTietCuaHang();
        setTextStartAndNew();
        updateStatus();
    }

    private void setTextStartAndNew() {
        txtMaCuaHang.setText("Mã cửa hàng");
        txtMaQuanLy.setText("Mã quản lý");
        txtDiaChi.setText("Địa chỉ");
        cboTrangThai.setSelectedIndex(0);

        styleAddHolder();
    }

    private void styleAddHolder() {
        DesignHelper.addPlaceHolderTextField(txtMaCuaHang);
        DesignHelper.addPlaceHolderTextField(txtMaQuanLy);
        DesignHelper.addPlaceHolderTextField(txtDiaChi);
    }

    private void setPlaceholderForSetForm() {
        DesignHelper.deletePlaceHolderTextField(txtMaCuaHang);
        Font font = txtMaCuaHang.getFont();
        font = font.deriveFont(Font.BOLD);
        txtMaCuaHang.setFont(font);
        DesignHelper.deletePlaceHolderTextField(txtMaQuanLy);
        DesignHelper.deletePlaceHolderTextField(txtDiaChi);
    }

    private void setTable() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("MÃ CỬA HÀNG");
        model.addColumn("MÃ QUẢN LÝ");
        model.addColumn("ĐỊA CHỈ");
        model.addColumn("TRẠNG THÁI");

        tblListCuaHang.setModel(model);
        DesignHelper.setTable(tblListCuaHang);
    }

    private void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblListCuaHang.getModel();
        model.setRowCount(0);
        try {
            String keyword = txtTimKiemCuaHang.getText();
            List<CuaHang> list = dao.selectByKeyWord(keyword);
            for (CuaHang ch : list) {
                if (!ch.getMaCH().equals("(Mã CH)")) {
                    model.addRow(new Object[]{
                        ch.getMaCH(),
                        ch.getMaQuanLy(),
                        ch.getDiaChi(),
                        ch.getTrangThai() ? "Còn hoạt động" : "Ngừng hoạt động"});
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void find() {
        this.fillTable();
        this.row = -1;
        this.clearForm();
        this.updateStatus();
    }

    private CuaHang getForm() {
        CuaHang ch = new CuaHang();
        ch.setMaCH(txtMaCuaHang.getText());
        ch.setMaQuanLy(txtMaQuanLy.getText());
        boolean trangThai = false;
        if (cboTrangThai.getSelectedIndex() == 1) {
            trangThai = true;
        }
        if (cboTrangThai.getSelectedIndex() == 2) {
            trangThai = false;
        }
        ch.setTrangThai(trangThai);

        ch.setDiaChi(txtDiaChi.getText());
        return ch;
    }

    private void setForm(CuaHang ch) {
        txtMaCuaHang.setText(ch.getMaCH());
        txtMaQuanLy.setText(ch.getMaQuanLy());
        String trangThai;
        if (ch.getTrangThai() == true) {
            trangThai = "Còn hoạt động";
        } else {
            trangThai = "Ngừng hoạt động";
        }
        cboTrangThai.setSelectedItem(trangThai);
        txtDiaChi.setText(ch.getDiaChi());
    }

    private void edit() {
        String maCH = (String) tblListCuaHang.getValueAt(this.row, 0);
        CuaHang ch = dao.selectById(maCH);
        this.setPlaceholderForSetForm();
        this.setForm(ch);
        this.updateStatus();
    }

    private void clearForm() {
        CuaHang ch = new CuaHang();
        this.setForm(ch);
        this.setTextStartAndNew();
        this.row = -1;
        this.updateStatus();
    }

    private void insert() {
        CuaHang ch = getForm();
        try {
            dao.insert(ch);
            this.fillTable();
            MsgBox.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại \n" + e);
        }
    }

    private void update() {
        CuaHang ch = getForm();
        try {
            dao.update(ch);
            this.fillTable();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại \n" + e);
        }
    }

    private void delete() {
        try {
            String maCH = txtMaCuaHang.getText();
            dao.delete(maCH);
            this.fillTable();
            MsgBox.alert(this, "Xóa thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Xóa thất bại");
        }
    }

    private void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblListCuaHang.getRowCount() - 1);

        // trạng thái form
        txtMaCuaHang.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnXoa.setEnabled(edit);
        btnSua.setEnabled(edit);

        // điều khiển
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);

        // nút trạng thái
        DesignHelper.setButtonBackgroundColor(btnThem, new Color(51, 255, 0), new Color(102, 255, 102));
        DesignHelper.setButtonBackgroundColor(btnXoa, new Color(255, 0, 0), new Color(255, 102, 102));
        DesignHelper.setButtonBackgroundColor(btnSua, new Color(255, 255, 0), new Color(255, 255, 153));

        // nút điều khiển
        DesignHelper.setButtonBackgroundColor(new Color(153, 204, 255), new Color(204, 255, 255),
                btnFirst, btnPrev, btnNext, btnLast);

    }
    // cap nhat cua hang chi tiet
    CuaHangDAO chdao = new CuaHangDAO();
    ChiTietCuaHangDAO ctchdao = new ChiTietCuaHangDAO();

    private void fillComboBoxCuaHang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboCuaHang.getModel();
        model.removeAllElements();
        List<CuaHang> list = chdao.selectAll();
//        Object[] tatcaObject = {"Tất cả", "Tất cả", "Tất cả"};
//        model.addElement(tatcaObject);
        model.addElement(new CuaHang("Tất cả", "", "cửa hàng", true));
        for (CuaHang cd : list) {
            model.addElement(cd);
        }
    }

    private void fillToTableChiTietCuaHang() {
        DefaultTableModel model = (DefaultTableModel) tblListCuaHangChiTiet.getModel();
        model.setRowCount(0);
        String keyword = txtTimKiemChiTiet.getText();
        try {
            if (cboCuaHang.getSelectedIndex() == 0) {

                List<ChiTietCuaHang> cuaHangALL = ctchdao.selectByMaCuaHang("", keyword);
                for (ChiTietCuaHang ctch : cuaHangALL) {
                    Object[] row = {ctch.getMaCuaHang(), ctch.getMaSanPham(), ctch.getSoLuong()};
                    model.addRow(row);
                }
            } else {

                CuaHang cuaHang = (CuaHang) cboCuaHang.getSelectedItem();

                if (cuaHang != null) {

                    List<ChiTietCuaHang> list = ctchdao.selectByMaCuaHang(cuaHang.getMaCH(), keyword);
                    for (ChiTietCuaHang ctch : list) {
                        Object[] row = {ctch.getMaCuaHang(), ctch.getMaSanPham(), ctch.getSoLuong()};
                        model.addRow(row);
                    }
                }
            }

        } catch (Exception e) {
            // System.out.println("Lỗi nhẹ thôi ko có gì hết! để tb cho vui !");

        }
    }
    
    void first() {
        row = 0;
        edit();
    }

    void prev() {
        if (row > 0) {
            row--;
            edit();
        }
    }

    void next() {
        if (row < tblListCuaHang.getRowCount() - 1) {
            row++;
            edit();
        }
    }

    void last() {
        row = tblListCuaHang.getRowCount() - 1;
        edit();
    }
}
