/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Sell.UI;

import com.Sell.DAO.ChiTietCuaHangDAO;
import com.Sell.DAO.CuaHangDAO;
import com.Sell.DAO.HoaDonBanHang_Dao;
import com.Sell.DAO.HoaDonChiTiet_DAO;
import com.Sell.DAO.KhachHangDAO;
import com.Sell.DAO.SanPhamDAO;
import com.Sell.Helper.DateHelper;
import com.Sell.entity.ChiTietCuaHang;
import com.Sell.entity.CuaHang;
import com.Sell.entity.HoaDonBanHang;
import com.Sell.entity.HoaDonChiTiet;
import com.Sell.entity.KhachHang;
import com.Sell.entity.SanPham;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class QL_HoaDon_Trieu extends javax.swing.JFrame {

    /**
     * Creates new form QL_HoaDon_Trieu
     */
    public QL_HoaDon_Trieu() {
        initComponents();
        this.setLocationRelativeTo(null);
        fillComboBoxCuaHang();
        fillComboBoxKhachHang();
        fillComboBoxSanPham();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSearch = new javax.swing.JPanel();
        cboCuaHang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiemChiTiet = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblListCuaHangChiTiet = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSoHoaDOn = new javax.swing.JTextField();
        panelKhachHang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboKhachHang = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtDt = new javax.swing.JTextField();
        btnThemHD = new javax.swing.JButton();
        txtDiaChi = new javax.swing.JTextField();
        panelKhachHang1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboSanPham = new javax.swing.JComboBox<>();
        txtNhaSx = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDonGIa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        panelKhachHang2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblListCuaHangChiTiet1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnThemVaoHoaDon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelSearch.setBackground(new java.awt.Color(255, 255, 255));

        cboCuaHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCuaHang.setPreferredSize(new java.awt.Dimension(300, 30));
        cboCuaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCuaHangActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TÌM KIẾM SP");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 40));

        txtTimKiemChiTiet.setPreferredSize(new java.awt.Dimension(400, 30));
        txtTimKiemChiTiet.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemChiTietCaretUpdate(evt);
            }
        });
        txtTimKiemChiTiet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemChiTietFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemChiTietFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panelSearchLayout = new javax.swing.GroupLayout(panelSearch);
        panelSearch.setLayout(panelSearchLayout);
        panelSearchLayout.setHorizontalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(cboCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTimKiemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelSearchLayout.setVerticalGroup(
            panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(panelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1))
        );

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(null);

        tblListCuaHangChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Cửa hàng", "Mã Sản Phẩm", "Số lượng"
            }
        ));
        tblListCuaHangChiTiet.setGridColor(new java.awt.Color(255, 255, 255));
        tblListCuaHangChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListCuaHangChiTietMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblListCuaHangChiTiet);

        jLabel1.setText("Số hóa đơn");

        panelKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        jLabel3.setText("Họ và tên");

        jLabel4.setText("Địa chỉ");

        jLabel5.setText("Số ĐT");

        jLabel6.setText("Email");

        cboKhachHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboKhachHangActionPerformed(evt);
            }
        });

        txtEmail.setEditable(false);

        txtDt.setEditable(false);

        btnThemHD.setText("Thêm HD");
        btnThemHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHDActionPerformed(evt);
            }
        });

        txtDiaChi.setEditable(false);

        javax.swing.GroupLayout panelKhachHangLayout = new javax.swing.GroupLayout(panelKhachHang);
        panelKhachHang.setLayout(panelKhachHangLayout);
        panelKhachHangLayout.setHorizontalGroup(
            panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKhachHangLayout.createSequentialGroup()
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKhachHangLayout.createSequentialGroup()
                        .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDt)
                            .addComponent(cboKhachHang, 0, 150, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKhachHangLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(6, 6, 6)))
                        .addGap(18, 18, 18)
                        .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelKhachHangLayout.createSequentialGroup()
                        .addComponent(btnThemHD, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelKhachHangLayout.setVerticalGroup(
            panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKhachHangLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(cboKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(txtDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnThemHD)
                .addGap(21, 21, 21))
        );

        panelKhachHang1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sản phẩm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        jLabel7.setText("Tên SP");

        jLabel9.setText("Nhà SX");

        cboSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSanPhamActionPerformed(evt);
            }
        });

        txtNhaSx.setEditable(false);

        jLabel11.setText("jLabel11");

        jLabel12.setText("Đơn giá");

        txtDonGIa.setEditable(false);

        jLabel13.setText("Số lượng");

        javax.swing.GroupLayout panelKhachHang1Layout = new javax.swing.GroupLayout(panelKhachHang1);
        panelKhachHang1.setLayout(panelKhachHang1Layout);
        panelKhachHang1Layout.setHorizontalGroup(
            panelKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKhachHang1Layout.createSequentialGroup()
                .addGroup(panelKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelKhachHang1Layout.createSequentialGroup()
                        .addGroup(panelKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGroup(panelKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelKhachHang1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboSanPham, 0, 147, Short.MAX_VALUE))
                            .addGroup(panelKhachHang1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(txtNhaSx))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelKhachHang1Layout.createSequentialGroup()
                        .addGroup(panelKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDonGIa)
                            .addComponent(txtSoLuong))))
                .addGap(90, 90, 90)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        panelKhachHang1Layout.setVerticalGroup(
            panelKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKhachHang1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cboSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(panelKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNhaSx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDonGIa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelKhachHang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelKhachHang1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelKhachHang2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa đơn chi tiết", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 16))); // NOI18N

        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.setBorder(null);

        tblListCuaHangChiTiet1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Sản Phẩm", "Số lượng", "Đơn giá"
            }
        ));
        tblListCuaHangChiTiet1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(tblListCuaHangChiTiet1);

        javax.swing.GroupLayout panelKhachHang2Layout = new javax.swing.GroupLayout(panelKhachHang2);
        panelKhachHang2.setLayout(panelKhachHang2Layout);
        panelKhachHang2Layout.setHorizontalGroup(
            panelKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKhachHang2Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelKhachHang2Layout.setVerticalGroup(
            panelKhachHang2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKhachHang2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Tổng tiền");

        jButton1.setText("Xóa sản phẩm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hủy hóa đơn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Thanh toán");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnThemVaoHoaDon.setText("Thêm vào hóa đơn");
        btnThemVaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemVaoHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelKhachHang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemVaoHoaDon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelKhachHang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(14, 14, 14)
                                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSoHoaDOn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSoHoaDOn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelKhachHang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelKhachHang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(btnThemVaoHoaDon))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboCuaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCuaHangActionPerformed
        fillToTableChiTietCuaHang();
    }//GEN-LAST:event_cboCuaHangActionPerformed

    private void txtTimKiemChiTietCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemChiTietCaretUpdate
        fillToTableChiTietCuaHang();
    }//GEN-LAST:event_txtTimKiemChiTietCaretUpdate

    private void txtTimKiemChiTietFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemChiTietFocusGained

    }//GEN-LAST:event_txtTimKiemChiTietFocusGained

    private void txtTimKiemChiTietFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemChiTietFocusLost

    }//GEN-LAST:event_txtTimKiemChiTietFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tongTien();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnThemVaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemVaoHoaDonActionPerformed
        HoaDonChiTiet_DAO hdctdao = new HoaDonChiTiet_DAO();
        HoaDonChiTiet hd = new HoaDonChiTiet();
        SanPham sp = (SanPham) cboSanPham.getSelectedItem();
        hd.setMaHDBan(txtSoHoaDOn.getText());
        hd.setMaSanPham(sp.getMaSanPham());
        hd.setSoLuong(txtSoLuong.getText());
        hd.setThanhTien(sp.getGiaTien());
        try {
            hdctdao.insert(hd);
            loadHoaDonChiTietTable();
            System.out.println("thanh cong");
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_btnThemVaoHoaDonActionPerformed

    private void cboKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboKhachHangActionPerformed
        fillToPanelKhachHang();

    }//GEN-LAST:event_cboKhachHangActionPerformed

    private void tblListCuaHangChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListCuaHangChiTietMouseClicked
        editSanPham();
    }//GEN-LAST:event_tblListCuaHangChiTietMouseClicked

    private void btnThemHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHDActionPerformed
        HoaDonBanHang_Dao hdbhdao = new HoaDonBanHang_Dao();
        HoaDonBanHang hd = new HoaDonBanHang();
        KhachHang kh = (KhachHang) cboKhachHang.getSelectedItem();
        hd.setMaHDBan(txtSoHoaDOn.getText());
        hd.setMaKhachHang(kh.getMaKhachHang());
        hd.setNgayBan(DateHelper.now());
        hd.setNoiDung("noi dung dang trong");
        hd.setTrangThai(true);
        hd.setMaNhanVien("NV01");
        hd.setMaCuaHang("CH001");
        hd.setMaGiamGia("null");
        try {
            hdbhdao.insert(hd);
            System.out.println("them hoa don moi thanh cong");
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_btnThemHDActionPerformed

    private void cboSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSanPhamActionPerformed

    }//GEN-LAST:event_cboSanPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_HoaDon_Trieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_HoaDon_Trieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_HoaDon_Trieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_HoaDon_Trieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QL_HoaDon_Trieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemHD;
    private javax.swing.JButton btnThemVaoHoaDon;
    private javax.swing.JComboBox<String> cboCuaHang;
    private javax.swing.JComboBox<String> cboKhachHang;
    private javax.swing.JComboBox<String> cboSanPham;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel panelKhachHang;
    private javax.swing.JPanel panelKhachHang1;
    private javax.swing.JPanel panelKhachHang2;
    private javax.swing.JPanel panelSearch;
    private javax.swing.JTable tblListCuaHangChiTiet;
    private javax.swing.JTable tblListCuaHangChiTiet1;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDonGIa;
    private javax.swing.JTextField txtDt;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNhaSx;
    private javax.swing.JTextField txtSoHoaDOn;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTimKiemChiTiet;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
    ChiTietCuaHangDAO ctchdao = new ChiTietCuaHangDAO();
    CuaHangDAO chdao = new CuaHangDAO();
    KhachHangDAO khdao = new KhachHangDAO();
    SanPhamDAO spdao = new SanPhamDAO();

    private void fillComboBoxCuaHang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboCuaHang.getModel();
        model.removeAllElements();
        List<CuaHang> list = chdao.selectAll();
        model.addElement(new CuaHang("Tất cả", "", "cửa hàng", true));
        for (CuaHang cd : list) {
            model.addElement(cd);
        }
    }

    private void fillToTableChiTietCuaHang() {
        DefaultTableModel model = (DefaultTableModel) tblListCuaHangChiTiet.getModel();
        model.setRowCount(0);
        String keyword = txtTimKiemChiTiet.getText();
        try {
            if (cboCuaHang.getSelectedIndex() == 0) {

                List<ChiTietCuaHang> cuaHangALL = ctchdao.selectByMaCuaHang("", keyword);
                for (ChiTietCuaHang ctch : cuaHangALL) {
                    Object[] row = {ctch.getMaCuaHang(), ctch.getMaSanPham(), ctch.getSoLuong()};
                    model.addRow(row);
                }
            } else {

                CuaHang cuaHang = (CuaHang) cboCuaHang.getSelectedItem();

                if (cuaHang != null) {

                    List<ChiTietCuaHang> list = ctchdao.selectByMaCuaHang(cuaHang.getMaCH(), keyword);
                    for (ChiTietCuaHang ctch : list) {
                        Object[] row = {ctch.getMaCuaHang(), ctch.getMaSanPham(), ctch.getSoLuong()};
                        model.addRow(row);
                    }
                }
            }

        } catch (Exception e) {
            // System.out.println("Lỗi nhẹ thôi ko có gì hết! để tb cho vui !");

        }
    }

    private void fillComboBoxKhachHang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboKhachHang.getModel();
        model.removeAllElements();
        List<KhachHang> list = khdao.selectAll();
        for (KhachHang cd : list) {
            model.addElement(cd);
        }
    }

    private void fillComboBoxSanPham() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboSanPham.getModel();
        model.removeAllElements();
        List<SanPham> list = spdao.selectAll();
        for (SanPham cd : list) {
            model.addElement(cd);
        }
    }

    private void fillToPanelKhachHang() {
        KhachHang kh = (KhachHang) cboKhachHang.getSelectedItem();
        try {
            txtDiaChi.setText(kh.getDiaChi());
            txtEmail.setText(kh.getEmail());
            txtDt.setText(kh.getDienThoai());
        } catch (Exception e) {
        }
    }

    void editSanPham() {
        int row = tblListCuaHangChiTiet.getSelectedRow();
        String maSP = (String) tblListCuaHangChiTiet.getValueAt(row, 1);
        SanPham sp = spdao.selectById(maSP);
        cboSanPham.setSelectedItem(sp);
        txtNhaSx.setText(sp.getNhaSX());
        txtSoLuong.setText("0");
        txtDonGIa.setText(sp.getGiaTien() + "");

    }

    private void loadHoaDonChiTietTable() {
        DefaultTableModel model = (DefaultTableModel) tblListCuaHangChiTiet1.getModel();
        model.setRowCount(0);
        try {
            HoaDonChiTiet_DAO dao = new HoaDonChiTiet_DAO();
            List<HoaDonChiTiet> list = dao.selectAll(txtSoHoaDOn.getText());
            for (HoaDonChiTiet ch : list) {
                model.addRow(new Object[]{
                    ch.getMaSanPham(),
                    ch.getSoLuong(),
                    ch.getThanhTien(),});
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void tongTien() {
        int row = tblListCuaHangChiTiet1.getRowCount(); 
        System.out.println(row);
        float tong = 0;
        for (int i = 0; i < row; i++) {
            float soLuong = Float.parseFloat(tblListCuaHangChiTiet1.getValueAt(i, 1) + "");
            System.out.println("soluong:" + soLuong);
            float donGia = Float.parseFloat(tblListCuaHangChiTiet1.getValueAt(i, 2).toString());
            System.out.println("don gia:" + donGia);

            tong = tong + soLuong * donGia;
        }
        txtTongTien.setText(tong + "");
    }

}
