/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Sell.UI;

import com.Sell.DAO.ChiTietCuaHangDAO;
import com.Sell.DAO.CuaHangDAO;
import com.Sell.DAO.HinhAnhDao;
import com.Sell.DAO.HoaDonBanHang_Dao;
import com.Sell.DAO.HoaDonChiTiet_DAO;
import com.Sell.DAO.KhachHangDAO;
import com.Sell.DAO.LoaiHangDAO;
import com.Sell.DAO.NhanVien_Dao;
import com.Sell.DAO.SanPhamDAO;
import com.Sell.Helper.Auth;
import com.Sell.Helper.DateHelper;
import com.Sell.Helper.DesignHelper;
import com.Sell.Helper.ImageHelper;
import com.Sell.Helper.MsgBox;
import com.Sell.entity.ChiTietCuaHang;
import com.Sell.entity.CuaHang;
import com.Sell.entity.HinhAnh;
import com.Sell.entity.HoaDonBanHang;
import com.Sell.entity.HoaDonChiTiet;
import com.Sell.entity.KhachHang;
import com.Sell.entity.LoaiHang;
import com.Sell.entity.NhanVien;
import com.Sell.entity.SanPham;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NguyenTruongChinh
 */
public class QL_HoaDonBanHang extends javax.swing.JPanel {

    List<HinhAnh> listHinhAnh = new ArrayList<>();
    int hinhIndex = -1;

    /**
     * Creates new form QL_HoaDon
     */
    public QL_HoaDonBanHang() {
        initComponents();
        init();
        jScrollPane1.getVerticalScrollBar().setUnitIncrement(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        panelHoaDonChiTiet = new javax.swing.JPanel();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel7 = new javax.swing.JLabel();
        btnBanHang = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        panelSearch1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTimKiem1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();
        panelBanHang = new javax.swing.JPanel();
        panelTitle = new com.k33ptoo.components.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        btnXemTableChiTiet1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        panelSearch2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChiTietCuaHang = new javax.swing.JTable();
        cboMaCuaHang = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        txtTienKhachDua = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTienTraLai = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnXoaHD = new javax.swing.JButton();
        btnHuyHoaDon = new javax.swing.JButton();
        btnXuatHoaDon = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cboTenKhachHang = new javax.swing.JComboBox<>();
        txtDiaChi = new javax.swing.JTextField();
        txtDienThoai = new javax.swing.JTextField();
        txtNguoiTao = new javax.swing.JTextField();
        btnAddKHToHoaDon = new javax.swing.JButton();
        btnDeleteKHToHoaDon = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblChiTietHoaDon = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        cboLoaiSanPham = new javax.swing.JComboBox<>();
        cboTenSanPham = new javax.swing.JComboBox<>();
        txtNhaSX = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        lblCong = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblTru = new javax.swing.JLabel();
        lblHinhAnh = new javax.swing.JLabel();
        btnThemSPToHoaDon = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnPrevHinh = new javax.swing.JButton();
        btnNextHinh = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1200, 950));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1010, 500));

        jPanel3.setPreferredSize(new java.awt.Dimension(1008, 950));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1210, 1000));
        jPanel4.setLayout(new java.awt.CardLayout());

        panelHoaDonChiTiet.setLayout(new java.awt.BorderLayout());

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(102, 216, 211));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 185, 215));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1010, 50));
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kGradientPanel1panelInputMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TRANG CHỦ/ QUẢN LÝ KHÁCH HÀNG");
        jLabel7.setPreferredSize(new java.awt.Dimension(210, 50));

        btnBanHang.setBackground(new java.awt.Color(255, 153, 0));
        btnBanHang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBanHang.setText("BÁN HÀNG");
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 823, Short.MAX_VALUE)
                .addComponent(btnBanHang)
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBanHang)))
        );

        panelHoaDonChiTiet.add(kGradientPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.BorderLayout());

        panelSearch1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("TÌM KIẾM");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 40));
        panelSearch1.add(jLabel5);

        txtTimKiem1.setPreferredSize(new java.awt.Dimension(400, 30));
        txtTimKiem1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiem1CaretUpdate(evt);
            }
        });
        panelSearch1.add(txtTimKiem1);

        jPanel5.add(panelSearch1, java.awt.BorderLayout.PAGE_START);

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setBorder(null);

        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblHoaDonChiTiet.setGridColor(new java.awt.Color(255, 255, 255));
        tblHoaDonChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonChiTietMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblHoaDonChiTietMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(tblHoaDonChiTiet);

        jPanel5.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        panelHoaDonChiTiet.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel4.add(panelHoaDonChiTiet, "card3");

        panelBanHang.setLayout(new java.awt.BorderLayout());

        panelTitle.setkBorderRadius(0);
        panelTitle.setkEndColor(new java.awt.Color(102, 216, 211));
        panelTitle.setkGradientFocus(1000);
        panelTitle.setkStartColor(new java.awt.Color(0, 185, 215));
        panelTitle.setPreferredSize(new java.awt.Dimension(1150, 50));
        panelTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTitleMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TRANG CHỦ/ QUẢN LÝ BÁN HÀNG");
        jLabel6.setPreferredSize(new java.awt.Dimension(210, 50));

        btnXemTableChiTiet1.setBackground(new java.awt.Color(255, 153, 51));
        btnXemTableChiTiet1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXemTableChiTiet1.setText("XEM CHI TIẾT HÓA ĐƠN");
        btnXemTableChiTiet1.setPreferredSize(new java.awt.Dimension(200, 30));
        btnXemTableChiTiet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTableChiTiet1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 732, Short.MAX_VALUE)
                .addComponent(btnXemTableChiTiet1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addGroup(panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXemTableChiTiet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelBanHang.add(panelTitle, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(1205, 700));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setMinimumSize(new java.awt.Dimension(1200, 100));
        jPanel8.setPreferredSize(new java.awt.Dimension(1180, 900));

        panelSearch2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("TÌM KIẾM SP");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 45));

        txtTimKiem.setPreferredSize(new java.awt.Dimension(400, 30));
        txtTimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemCaretUpdate(evt);
            }
        });
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Số hóa đơn");

        javax.swing.GroupLayout panelSearch2Layout = new javax.swing.GroupLayout(panelSearch2);
        panelSearch2.setLayout(panelSearch2Layout);
        panelSearch2Layout.setHorizontalGroup(
            panelSearch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearch2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSearch2Layout.setVerticalGroup(
            panelSearch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSearch2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1)
                .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "2. CHỌN SẢN PHẨM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(550, 352));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tblChiTietCuaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblChiTietCuaHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietCuaHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblChiTietCuaHang);

        cboMaCuaHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhập mã hóa đơn, mã nhân viên" }));
        cboMaCuaHang.setPreferredSize(new java.awt.Dimension(64, 30));
        cboMaCuaHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMaCuaHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboMaCuaHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cboMaCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "5. THANH TOÁN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N
        jPanel11.setPreferredSize(new java.awt.Dimension(1000, 191));

        txtTienKhachDua.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Tổng tiền");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("VNĐ");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Tiền khách đưa");

        txtTongTien.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("VNĐ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Tiền trả lại");

        txtTienTraLai.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("VNĐ");

        btnXoaHD.setText("Xóa hóa đơn");
        btnXoaHD.setPreferredSize(new java.awt.Dimension(150, 30));
        btnXoaHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHDActionPerformed(evt);
            }
        });

        btnHuyHoaDon.setText("Hủy hóa đơn");
        btnHuyHoaDon.setPreferredSize(new java.awt.Dimension(150, 30));

        btnXuatHoaDon.setText("Xuất hóa đơn");
        btnXuatHoaDon.setPreferredSize(new java.awt.Dimension(150, 30));

        btnThanhToan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThanhToan.setText("THANH TOÁN");
        btnThanhToan.setPreferredSize(new java.awt.Dimension(150, 30));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14))
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(txtTienTraLai, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16))))
                    .addComponent(jLabel11))
                .addGap(139, 139, 139)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnXoaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(200, 200, 200)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(btnXoaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(btnHuyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTienTraLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "1. THÔNG TIN KHÁCH HÀNG", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N

        cboTenKhachHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTenKhachHang.setPreferredSize(new java.awt.Dimension(64, 30));
        cboTenKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenKhachHangActionPerformed(evt);
            }
        });

        btnAddKHToHoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddKHToHoaDon.setText("Thêm vào hóa đơn");
        btnAddKHToHoaDon.setPreferredSize(new java.awt.Dimension(150, 30));
        btnAddKHToHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddKHToHoaDonActionPerformed(evt);
            }
        });

        btnDeleteKHToHoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeleteKHToHoaDon.setText("Hoá đơn mới");
        btnDeleteKHToHoaDon.setPreferredSize(new java.awt.Dimension(150, 30));
        btnDeleteKHToHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteKHToHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cboTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAddKHToHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteKHToHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboTenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDiaChi))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNguoiTao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddKHToHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteKHToHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "4. CHI TIẾT HÓA ĐƠN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tblChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblChiTietHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChiTietHoaDonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblChiTietHoaDon);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "3. THÔNG TIN SẢN PHẨM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N
        jPanel10.setPreferredSize(new java.awt.Dimension(550, 277));

        cboLoaiSanPham.setPreferredSize(new java.awt.Dimension(64, 30));
        cboLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiSanPhamActionPerformed(evt);
            }
        });

        cboTenSanPham.setPreferredSize(new java.awt.Dimension(64, 30));
        cboTenSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTenSanPhamActionPerformed(evt);
            }
        });

        lblCong.setBackground(new java.awt.Color(204, 204, 204));
        lblCong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCong.setText("+");
        lblCong.setOpaque(true);
        lblCong.setPreferredSize(new java.awt.Dimension(30, 30));
        lblCong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCongMouseClicked(evt);
            }
        });

        lblSoLuong.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSoLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoLuong.setText("0");
        lblSoLuong.setPreferredSize(new java.awt.Dimension(30, 30));

        lblTru.setBackground(new java.awt.Color(204, 204, 204));
        lblTru.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTru.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTru.setText("-");
        lblTru.setOpaque(true);
        lblTru.setPreferredSize(new java.awt.Dimension(30, 30));
        lblTru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTruMouseClicked(evt);
            }
        });

        lblHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhAnh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnThemSPToHoaDon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemSPToHoaDon.setText("Thêm vào hóa đơn");
        btnThemSPToHoaDon.setPreferredSize(new java.awt.Dimension(170, 30));
        btnThemSPToHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPToHoaDonActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Số lượng");
        jLabel10.setPreferredSize(new java.awt.Dimension(51, 30));

        btnPrevHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/btnPrev-QLHDBanHang-Actions-arrow-left-icon.png"))); // NOI18N
        btnPrevHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevHinhActionPerformed(evt);
            }
        });

        btnNextHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/btnNext-QLHDBanHang-Actions-arrow-right-icon.png"))); // NOI18N
        btnNextHinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextHinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboTenSanPham, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDonGia)
                    .addComponent(cboLoaiSanPham, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNhaSX, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(btnThemSPToHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(btnPrevHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNextHinh, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cboLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboTenSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNhaSX, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(btnNextHinh))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(btnPrevHinh)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThemSPToHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSearch2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(panelSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        jPanel6.add(jPanel8);

        panelBanHang.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel4.add(panelBanHang, "card2");

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void panelTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTitleMouseClicked

    }//GEN-LAST:event_panelTitleMouseClicked

    private void txtTimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemCaretUpdate

    }//GEN-LAST:event_txtTimKiemCaretUpdate

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained

    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtTimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusLost

    }//GEN-LAST:event_txtTimKiemFocusLost

    private void cboLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiSanPhamActionPerformed
        // TODO add your handling code here:
        try {
            this.fillComboBoxTenSanPham();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboLoaiSanPhamActionPerformed

    private void lblCongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCongMouseClicked
        // TODO add your handling code here:
        int soLuong = Integer.parseInt(lblSoLuong.getText());
        soLuong++;
        lblSoLuong.setText(String.valueOf(soLuong));
        lblTru.setEnabled(true);
    }//GEN-LAST:event_lblCongMouseClicked

    private void lblTruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTruMouseClicked
        // TODO add your handling code here:
        int soLuong = Integer.parseInt(lblSoLuong.getText());
        if (soLuong <= 0) {
            lblTru.setEnabled(false);
        } else {
            soLuong--;
            lblSoLuong.setText(String.valueOf(soLuong));
        }
    }//GEN-LAST:event_lblTruMouseClicked

    private void btnXoaHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHDActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaHDActionPerformed

    private void btnThemSPToHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPToHoaDonActionPerformed
        // TODO add your handling code here:
        this.themSPToHoaDon();
    }//GEN-LAST:event_btnThemSPToHoaDonActionPerformed

    private void cboTenKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenKhachHangActionPerformed
        // TODO add your handling code here:
        this.fillToPanelKhachHang();
    }//GEN-LAST:event_cboTenKhachHangActionPerformed

    private void tblChiTietCuaHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietCuaHangMouseClicked
        int row = tblChiTietCuaHang.getSelectedRow();
        if (row < 0) {
            return;
        }
        String maSP = (String) tblChiTietCuaHang.getValueAt(row, 1);
        SanPham sp = spdao.selectById(maSP);
        listHinhAnh = new HinhAnhDao().selectAllById(maSP);
        if (!listHinhAnh.isEmpty()) {
            this.hinhIndex = 0;
            lblHinhAnh.setIcon(ImageHelper.revertFromArrayByte(lblHinhAnh, listHinhAnh.get(0).getHinhAnh()));
        }
        fillComboBoxLoaiHang();
        fillComboBoxTenSanPham();
        this.editSanPham(sp);
    }//GEN-LAST:event_tblChiTietCuaHangMouseClicked

    private void tblChiTietHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChiTietHoaDonMouseClicked
        // TODO add your handling code here:
        this.hoaDonChiTietToForm();
        int rowCTHD = tblChiTietHoaDon.getSelectedRow();
        String maSP = (String) tblChiTietHoaDon.getValueAt(rowCTHD, 0);
        SanPham sp = spdao.selectById(maSP);
        listHinhAnh = new HinhAnhDao().selectAllById(maSP);
        if (!listHinhAnh.isEmpty()) {
            this.hinhIndex = 0;
            lblHinhAnh.setIcon(ImageHelper.revertFromArrayByte(lblHinhAnh, listHinhAnh.get(0).getHinhAnh()));
        }
    }//GEN-LAST:event_tblChiTietHoaDonMouseClicked

    private void btnAddKHToHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddKHToHoaDonActionPerformed
        // TODO add your handling code here:
        this.themTableHoaDon();
        fillComboBoxCuaHang();
    }//GEN-LAST:event_btnAddKHToHoaDonActionPerformed

    private void cboMaCuaHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMaCuaHangActionPerformed
        // TODO add your handling code here:
        this.fillToTableChiTietCuaHang();
    }//GEN-LAST:event_cboMaCuaHangActionPerformed

    private void cboTenSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTenSanPhamActionPerformed
//        try {
//            LoaiHang lh = (LoaiHang) cboLoaiSanPham.getSelectedItem();
//            SanPham sp = (SanPham) spdao.selectByMaLoaiHang(lh.getMaLoai());
//
//            txtNhaSX.setText(sp.getNhaSX());
//            lblSoLuong.setText("0");
//            txtDonGia.setText(sp.getGiaTien() + "");
//        } catch (Exception e) {
//            System.out.println("dong 773" + e);
//        }
    }//GEN-LAST:event_cboTenSanPhamActionPerformed

    private void kGradientPanel1panelInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1panelInputMouseClicked

    }//GEN-LAST:event_kGradientPanel1panelInputMouseClicked

    private void txtTimKiem1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiem1CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiem1CaretUpdate

    private void tblHoaDonChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonChiTietMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int row = tblHoaDonChiTiet.getSelectedRow();
            HoaDonBanHang_Dao hddao = new HoaDonBanHang_Dao();
            if (row < 0) {
                return;
            }
            String mahd = (String) tblHoaDonChiTiet.getValueAt(row, 0);
            HoaDonBanHang hd = hddao.selectById(mahd);
            QL_HoaDonBanHang ql = new QL_HoaDonBanHang();
            panelBanHang.setVisible(true);
            panelHoaDonChiTiet.setVisible(false);
            this.fillToForm(hd);
            txtMaHoaDon.setEnabled(false);
        }
    }//GEN-LAST:event_tblHoaDonChiTietMouseClicked

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        panelBanHang.setVisible(true);
        panelHoaDonChiTiet.setVisible(false);
    }//GEN-LAST:event_btnBanHangActionPerformed

    private void btnXemTableChiTiet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTableChiTiet1ActionPerformed
        // TODO add your handling code here:
        panelHoaDonChiTiet.setVisible(true);
        panelBanHang.setVisible(false);
    }//GEN-LAST:event_btnXemTableChiTiet1ActionPerformed

    private void tblHoaDonChiTietMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonChiTietMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_tblHoaDonChiTietMouseEntered

    private void btnNextHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextHinhActionPerformed
        if (listHinhAnh.size() <= 0) {
            return;
        }

        if (this.hinhIndex < listHinhAnh.size() - 1) {
            this.hinhIndex++;
        } else {
            this.hinhIndex = 0;
        }
        lblHinhAnh.setIcon(ImageHelper.revertFromArrayByte(lblHinhAnh, listHinhAnh.get(hinhIndex).getHinhAnh()));
    }//GEN-LAST:event_btnNextHinhActionPerformed

    private void btnPrevHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevHinhActionPerformed
        if (listHinhAnh.size() <= 0) {
            return;
        }
        
        if (this.hinhIndex == 0) {
            this.hinhIndex = listHinhAnh.size() - 1;
        } else {
            this.hinhIndex--;
        }
        lblHinhAnh.setIcon(ImageHelper.revertFromArrayByte(lblHinhAnh, listHinhAnh.get(hinhIndex).getHinhAnh()));
    }//GEN-LAST:event_btnPrevHinhActionPerformed

    private void btnDeleteKHToHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteKHToHoaDonActionPerformed
        txtMaHoaDon.setText("");
        txtNguoiTao.setText("");
        txtMaHoaDon.setEnabled(true);

        txtTongTien.setText("");
        txtTienKhachDua.setText("");
        txtTienTraLai.setText("");
        try {
            cboTenKhachHang.setSelectedIndex(0);
            cboMaCuaHang.setSelectedIndex(0);
            cboLoaiSanPham.setSelectedIndex(0);
            DefaultTableModel model = (DefaultTableModel) tblHoaDonChiTiet.getModel();
            model.setRowCount(0);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDeleteKHToHoaDonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddKHToHoaDon;
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnDeleteKHToHoaDon;
    private javax.swing.JButton btnHuyHoaDon;
    private javax.swing.JButton btnNextHinh;
    private javax.swing.JButton btnPrevHinh;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemSPToHoaDon;
    private javax.swing.JButton btnXemTableChiTiet1;
    private javax.swing.JButton btnXoaHD;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JComboBox<String> cboLoaiSanPham;
    private javax.swing.JComboBox<String> cboMaCuaHang;
    private javax.swing.JComboBox<String> cboTenKhachHang;
    private javax.swing.JComboBox<String> cboTenSanPham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblCong;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTru;
    private javax.swing.JPanel panelBanHang;
    private javax.swing.JPanel panelHoaDonChiTiet;
    private javax.swing.JPanel panelSearch1;
    private javax.swing.JPanel panelSearch2;
    private com.k33ptoo.components.KGradientPanel panelTitle;
    private javax.swing.JTable tblChiTietCuaHang;
    private javax.swing.JTable tblChiTietHoaDon;
    private javax.swing.JTable tblHoaDonChiTiet;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtNguoiTao;
    private javax.swing.JTextField txtNhaSX;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTienTraLai;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTimKiem1;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    void init() {
        setTable();
        fillComboBoxKhachHang();
        fillTableHoaDonBan();
        panelBanHang.setVisible(false);
        panelHoaDonChiTiet.setVisible(true);
    }

    void setTable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("MÃ CỬA HÀNG");
        model.addColumn("MÃ SẢN PHẨM");
        model.addColumn("MÃ SỐ LƯỢNG");
        tblChiTietCuaHang.setModel(model);
        DesignHelper.setTable(tblChiTietCuaHang);

        DefaultTableModel model2 = new DefaultTableModel();
        model2.addColumn("TÊN SẢN PHẨM");
        model2.addColumn("SỐ LƯỢNG");
        model2.addColumn("ĐƠN GIÁ");
        tblChiTietHoaDon.setModel(model2);
        DesignHelper.setTable(tblChiTietHoaDon);

        DefaultTableModel model3 = new DefaultTableModel();
        model3.addColumn("MÃ HÓA ĐƠN");
        model3.addColumn("MÃ KHÁCH HÀNG");
        model3.addColumn("NGÀY BÁN");
        model3.addColumn("NỘI DUNG");
        model3.addColumn("TRẠNG THÁI");
        model3.addColumn("MÃ NV");
        model3.addColumn("MÃ CH");
        model3.addColumn("MÃ GIẢM GIÁ");
        tblHoaDonChiTiet.setModel(model3);
        DesignHelper.setTable(tblHoaDonChiTiet);
    }

    KhachHangDAO khdao = new KhachHangDAO();
    CuaHangDAO chdao = new CuaHangDAO();
    LoaiHangDAO lhdao = new LoaiHangDAO();
    SanPhamDAO spdao = new SanPhamDAO();
    ChiTietCuaHangDAO ctchdao = new ChiTietCuaHangDAO();
    NhanVien_Dao nvdao = new NhanVien_Dao();

//    void fillComboboxTenKhachHang() {
//        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenKhachHang.getModel();
//        model.removeAllElements();
//        List<KhachHang> list = khdao.selectAll();
//        Date now = new Date();
//        model.addElement(new KhachHang("Mã KH", "Họ Tên", now, "", "", now, "", true));
//        for (KhachHang cd : list) {
//            model.addElement(cd);
//        }
//    }
    private void fillComboBoxKhachHang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenKhachHang.getModel();
        model.removeAllElements();
        List<KhachHang> list = khdao.selectAll();
        for (KhachHang cd : list) {
            model.addElement(cd);
        }
    }

    private void fillComboBoxCuaHang() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboMaCuaHang.getModel();
        model.removeAllElements();
        List<CuaHang> list = chdao.selectAll();
        model.addElement(new CuaHang("Tất cả", "", "cửa hàng", true));
        for (CuaHang cd : list) {
            model.addElement(cd);
        }
        try {
            NhanVien nv = nvdao.selectById(txtNguoiTao.getText());
            CuaHang ch = chdao.selectById(nv.getMaCuaHang());
            cboMaCuaHang.setSelectedItem(ch);
        } catch (Exception e) {
        }
    }

    private void fillToTableChiTietCuaHang() {
        DefaultTableModel model = (DefaultTableModel) tblChiTietCuaHang.getModel();
        model.setRowCount(0);
        String keyword = txtTimKiem.getText();
        try {
            if (cboMaCuaHang.getSelectedIndex() == 0) {

                List<ChiTietCuaHang> cuaHangALL = ctchdao.selectByMaCuaHang("", keyword);
                for (ChiTietCuaHang ctch : cuaHangALL) {
                    Object[] row = {ctch.getMaCuaHang(), ctch.getMaSanPham(), ctch.getSoLuong()};
                    model.addRow(row);
                }
            } else {

                CuaHang cuaHang = (CuaHang) cboMaCuaHang.getSelectedItem();

                if (cuaHang != null) {

                    List<ChiTietCuaHang> list = ctchdao.selectByMaCuaHang(cuaHang.getMaCH(), keyword);
                    for (ChiTietCuaHang ctch : list) {
                        Object[] row = {ctch.getMaCuaHang(), ctch.getMaSanPham(), ctch.getSoLuong()};
                        model.addRow(row);
                    }
                }
            }

        } catch (Exception e) {
            // System.out.println("Lỗi nhẹ thôi ko có gì hết! để tb cho vui !");

        }
    }

    void fillComboBoxLoaiHang() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        List<LoaiHang> list = lhdao.selectAll();
        model.addElement(new LoaiHang("Tất cả", "Tất cả ", "cửa hàng"));
        for (LoaiHang cd : list) {
            model.addElement(cd);
        }
        cboLoaiSanPham.setModel(model);
    }

    void fillComboBoxTenSanPham() {

        DefaultComboBoxModel model = (DefaultComboBoxModel) cboTenSanPham.getModel();
        try {
            model.removeAllElements();

        } catch (Exception e) {
        }
        LoaiHang loaiHang = (LoaiHang) cboLoaiSanPham.getSelectedItem();
        model.removeAllElements();
        if (true) {
            List<SanPham> list = spdao.selectByMaLoaiHang(loaiHang.getMaLoai());
            for (SanPham sp : list) {
                model.addElement(sp);
            }
        } else {
            model.removeAllElements();
        }
    }

    private void fillToPanelKhachHang() {
        KhachHang kh = (KhachHang) cboTenKhachHang.getSelectedItem();
        try {
            txtDiaChi.setText(kh.getDiaChi());
            txtDienThoai.setText(kh.getDienThoai());
            if (txtNguoiTao.getText().length() == 0) {
                txtNguoiTao.setText(Auth.user.getMaNV());
            }
        } catch (Exception e) {
        }
    }

    void editSanPham(SanPham sp) {

        //tim loai hang
        LoaiHang lh = lhdao.selectById(sp.getMaLoai());

        cboLoaiSanPham.setSelectedItem(lh);

        cboTenSanPham.setSelectedItem(sp);

        txtNhaSX.setText(sp.getNhaSX());
        txtDonGia.setText(sp.getGiaTien() + "");
        lblSoLuong.setText("0");

    }

    private void loadHoaDonChiTietTable() {
        DefaultTableModel model = (DefaultTableModel) tblChiTietHoaDon.getModel();
        model.setRowCount(0);
        try {
            HoaDonChiTiet_DAO dao = new HoaDonChiTiet_DAO();
            List<HoaDonChiTiet> list = dao.selectAll(txtMaHoaDon.getText());
            for (HoaDonChiTiet ch : list) {
                model.addRow(new Object[]{
                    ch.getMaSanPham(),
                    ch.getSoLuong(),
                    ch.getThanhTien(),});
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void tongTien() {
        int row = tblChiTietHoaDon.getRowCount();
        System.out.println(row);
        float tong = 0;
        for (int i = 0; i < row; i++) {
            float soLuong = Float.parseFloat(tblChiTietHoaDon.getValueAt(i, 1) + "");
            System.out.println("soluong:" + soLuong);
            float donGia = Float.parseFloat(tblChiTietHoaDon.getValueAt(i, 2).toString());
            System.out.println("don gia:" + donGia);

            tong = tong + soLuong * donGia;
        }
        txtTongTien.setText(tong + "");
    }

    void fillToForm(HoaDonBanHang hd) {
        txtMaHoaDon.setText(hd.getMaHDBan());
        KhachHang kh = khdao.selectById(hd.getMaKhachHang());
        cboTenKhachHang.setSelectedItem(kh);
        txtNguoiTao.setText(hd.getMaNhanVien());
        loadHoaDonChiTietTable();

    }

    private void hoaDonChiTietToForm() {
        HoaDonChiTiet_DAO hdctdao = new HoaDonChiTiet_DAO();
        HoaDonChiTiet hd = new HoaDonChiTiet();
        int row = tblChiTietHoaDon.getSelectedRow();
        String sp = tblChiTietHoaDon.getValueAt(row, 0) + "";

        SanPham spct = spdao.selectById(sp);
        cboTenSanPham.setSelectedItem(spct);
        txtNhaSX.setText(spct.getNhaSX());
        lblSoLuong.setText("0");
        txtDonGia.setText(spct.getGiaTien() + "");
    }

    private void delete() {
        int row = tblChiTietHoaDon.getSelectedRow();
        String HDChiTiet = tblChiTietHoaDon.getValueAt(row, 0) + "";
        if (MsgBox.confirm(this, "Bạn có muốn xóa hay không?")) {
            try {
                HoaDonChiTiet_DAO hdctdao = new HoaDonChiTiet_DAO();
                hdctdao.delete(txtMaHoaDon.getText(), HDChiTiet);
                this.loadHoaDonChiTietTable();
                tongTien();
                fillToTableChiTietCuaHang();
                MsgBox.alert(this, "Xóa thành công!");
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa thất bại!");
            }
        }
    }

    private void themSPToHoaDon() {
        HoaDonChiTiet_DAO hdctdao = new HoaDonChiTiet_DAO();
        HoaDonChiTiet hd = new HoaDonChiTiet();
        SanPham sp = (SanPham) cboTenSanPham.getSelectedItem();
        hd.setMaHDBan(txtMaHoaDon.getText());
        hd.setMaSanPham(sp.getMaSanPham());
        hd.setSoLuong(lblSoLuong.getText());
        hd.setThanhTien(sp.getGiaTien());
        try {
            hdctdao.insert(hd);
            loadHoaDonChiTietTable();
            tongTien();
            fillToTableChiTietCuaHang();
            MsgBox.alert(this, "Thêm sản phẩm vào hóa đơn thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm sản phẩm vào hóa đơn thất bại!");
        }
    }

    private void themTableHoaDon() {
        HoaDonBanHang_Dao hdbhdao = new HoaDonBanHang_Dao();
        HoaDonBanHang hd = new HoaDonBanHang();
        KhachHang kh = (KhachHang) cboTenKhachHang.getSelectedItem();
        hd.setMaHDBan(txtMaHoaDon.getText());
        hd.setMaKhachHang(kh.getMaKhachHang());
        hd.setNgayBan(DateHelper.now());
        hd.setNoiDung("noi dung dang trong");
        hd.setTrangThai(true);
        hd.setMaNhanVien(txtNguoiTao.getText());
        NhanVien nv = nvdao.selectById(txtNguoiTao.getText());
        hd.setMaCuaHang(nv.getMaCuaHang());
        hd.setMaGiamGia("1");
        try {
            hdbhdao.insert(hd);
            MsgBox.alert(this, "Thêm mới hóa đơn thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới hóa đơn thất bại!");
        }
    }

    /* HÓA ĐƠN CHI TIẾT */
    private void fillTableHoaDonBan() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        model.setRowCount(0);
        try {
            HoaDonBanHang_Dao dao = new HoaDonBanHang_Dao();
            List<HoaDonBanHang> list = dao.selectAll();
            for (HoaDonBanHang ch : list) {
                model.addRow(new Object[]{
                    ch.getMaHDBan(),
                    ch.getMaKhachHang(),
                    DateHelper.toString(ch.getNgayBan()),
                    ch.getNoiDung(),
                    ch.getTrangThai(),
                    ch.getMaNhanVien(),
                    ch.getMaCuaHang(),
                    ch.getMaGiamGia()});
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

}
