/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Sell.UI;

import com.Sell.entity.LoaiHang;
import com.Sell.DAO.LoaiHangDAO;
import com.Sell.Helper.DesignHelper;
import com.Sell.Helper.MsgBox;
import com.Sell.Helper.ValidationHelper;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NguyenTruongChinh
 */
public class QL_LoaiHang extends javax.swing.JPanel {

    int row = -1;

    /**
     * Creates new form LoaiHang
     */
    public QL_LoaiHang() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitle = new com.k33ptoo.components.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        panelContents = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelSanPham = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        panelInput = new javax.swing.JPanel();
        txtMaLoai = new javax.swing.JTextField();
        txtTenLoai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        panelFunction = new javax.swing.JPanel();
        btnMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        panelDieuKhien = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLoaiSanPham = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        panelTitle.setkBorderRadius(0);
        panelTitle.setkEndColor(new java.awt.Color(102, 216, 211));
        panelTitle.setkGradientFocus(1000);
        panelTitle.setkStartColor(new java.awt.Color(0, 185, 215));
        panelTitle.setPreferredSize(new java.awt.Dimension(1150, 50));
        panelTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelTitlepanelSanPhamMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TRANG CHỦ/ QUẢN LÝ LOẠI SẢN PHẨM");
        jLabel6.setPreferredSize(new java.awt.Dimension(210, 50));

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 754, Short.MAX_VALUE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(panelTitle, java.awt.BorderLayout.NORTH);

        panelContents.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(335, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ LOẠI SẢN PHẨM");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1panelSanPhamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelContents.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.CardLayout());

        panelSanPham.setPreferredSize(new java.awt.Dimension(1050, 509));
        panelSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSanPhamMouseClicked(evt);
            }
        });

        jPanel6.setPreferredSize(new java.awt.Dimension(1020, 499));

        jPanel7.setPreferredSize(new java.awt.Dimension(1010, 475));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7panelSanPhamMouseClicked(evt);
            }
        });

        panelInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelInputMouseClicked(evt);
            }
        });

        txtMaLoai.setPreferredSize(new java.awt.Dimension(80, 35));
        txtMaLoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaLoaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaLoaiFocusLost(evt);
            }
        });

        txtTenLoai.setPreferredSize(new java.awt.Dimension(80, 35));
        txtTenLoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenLoaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenLoaiFocusLost(evt);
            }
        });

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        txtGhiChu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGhiChuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGhiChuFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txtGhiChu);

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        btnMoi.setBackground(new java.awt.Color(51, 255, 255));
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/refresh-icon.png"))); // NOI18N
        btnMoi.setText(" MỚI");
        btnMoi.setPreferredSize(new java.awt.Dimension(120, 30));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(51, 255, 0));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/Add.png"))); // NOI18N
        btnThem.setText(" THÊM");
        btnThem.setPreferredSize(new java.awt.Dimension(120, 30));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 0, 0));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/Delete.png"))); // NOI18N
        btnXoa.setText(" XÓA");
        btnXoa.setPreferredSize(new java.awt.Dimension(120, 30));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 255, 0));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/UPDATE.png"))); // NOI18N
        btnSua.setText(" SỬA");
        btnSua.setPreferredSize(new java.awt.Dimension(120, 30));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFunctionLayout = new javax.swing.GroupLayout(panelFunction);
        panelFunction.setLayout(panelFunctionLayout);
        panelFunctionLayout.setHorizontalGroup(
            panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFunctionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        panelFunctionLayout.setVerticalGroup(
            panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFunctionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnFirst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFirst.setText("|<");
        btnFirst.setPreferredSize(new java.awt.Dimension(100, 25));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrev.setText("<<");
        btnPrev.setPreferredSize(new java.awt.Dimension(100, 25));
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext.setText(">>");
        btnNext.setPreferredSize(new java.awt.Dimension(100, 25));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLast.setText(">|");
        btnLast.setPreferredSize(new java.awt.Dimension(100, 25));
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDieuKhienLayout = new javax.swing.GroupLayout(panelDieuKhien);
        panelDieuKhien.setLayout(panelDieuKhienLayout);
        panelDieuKhienLayout.setHorizontalGroup(
            panelDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDieuKhienLayout.createSequentialGroup()
                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDieuKhienLayout.setVerticalGroup(
            panelDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tblLoaiSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaiSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLoaiSanPham);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelFunction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDieuKhien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(panelFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelDieuKhien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        panelSanPham.add(jPanel6);

        jPanel4.add(panelSanPham, "card2");

        panelContents.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(panelContents, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void panelTitlepanelSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelTitlepanelSanPhamMouseClicked
        JComponent component = (JComponent) evt.getSource();
        component.requestFocus();
    }//GEN-LAST:event_panelTitlepanelSanPhamMouseClicked

    private void jLabel1panelSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1panelSanPhamMouseClicked
        JComponent component = (JComponent) evt.getSource();
        component.requestFocus();
    }//GEN-LAST:event_jLabel1panelSanPhamMouseClicked

    private void txtMaLoaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaLoaiFocusGained
        if (txtMaLoai.getText().equals("Mã loại")) {
            DesignHelper.deletePlaceHolderTextField(txtMaLoai);
        }
    }//GEN-LAST:event_txtMaLoaiFocusGained

    private void txtMaLoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaLoaiFocusLost
        if (txtMaLoai.getText().trim().length() == 0) {
            DesignHelper.addPlaceHolderTextField(txtMaLoai, "Mã loại");
        }
    }//GEN-LAST:event_txtMaLoaiFocusLost

    private void txtTenLoaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenLoaiFocusGained
        if (txtTenLoai.getText().equals("Tên loại")) {
            DesignHelper.deletePlaceHolderTextField(txtTenLoai);
        }
    }//GEN-LAST:event_txtTenLoaiFocusGained

    private void txtTenLoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenLoaiFocusLost
        if (txtTenLoai.getText().trim().length() == 0) {
            txtTenLoai.setText("Tên loại");
            DesignHelper.addPlaceHolderTextField(txtTenLoai);
        }
    }//GEN-LAST:event_txtTenLoaiFocusLost

    private void txtGhiChuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGhiChuFocusGained
        if (txtGhiChu.getText().equals("Ghi chú")) {
            txtGhiChu.setText("");
            DesignHelper.deletePlaceHolderTextField(txtGhiChu);
        }
    }//GEN-LAST:event_txtGhiChuFocusGained

    private void txtGhiChuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGhiChuFocusLost
        if (txtGhiChu.getText().trim().length() == 0) {
            txtGhiChu.setText("Ghi chú");
            DesignHelper.addPlaceHolderTextField(txtGhiChu);
        }
    }//GEN-LAST:event_txtGhiChuFocusLost

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void tblLoaiSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiSanPhamMouseClicked
        this.row = tblLoaiSanPham.getSelectedRow();
        this.edit();
    }//GEN-LAST:event_tblLoaiSanPhamMouseClicked

    private void jPanel7panelSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7panelSanPhamMouseClicked
        JComponent component = (JComponent) evt.getSource();
        component.requestFocus();
    }//GEN-LAST:event_jPanel7panelSanPhamMouseClicked

    private void panelSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSanPhamMouseClicked
        JComponent component = (JComponent) evt.getSource();
        component.requestFocus();
    }//GEN-LAST:event_panelSanPhamMouseClicked

    private void panelInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelInputMouseClicked
        // TODO add your handling code here:
        JComponent component = (JComponent) evt.getSource();
        component.requestFocus();
    }//GEN-LAST:event_panelInputMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelContents;
    private javax.swing.JPanel panelDieuKhien;
    private javax.swing.JPanel panelFunction;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelSanPham;
    private com.k33ptoo.components.KGradientPanel panelTitle;
    private javax.swing.JTable tblLoaiSanPham;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtTenLoai;
    // End of variables declaration//GEN-END:variables

    LoaiHangDAO dao = new LoaiHangDAO();

    private void init() {
        setTextField();
        setTable();
        this.fillTable();
        updateStatus();
    }

    private void setTable() {
//        DefaultTableModel tblModel = new DefaultTableModel() {
//            @Override
//            public boolean isCellEditable(int row, int column) {
//                //all cells false
//                return false;
//            }
//        };
        String columns[] = {"MÃ LOẠI", "TÊN LOẠI", "GHI CHÚ"};
//        tblModel.setColumnIdentifiers(columns);
//
//        tblLoaiSanPham.setModel(tblModel);
//        tblLoaiSanPham.setSelectionMode(0);
        DesignHelper.setTable(tblLoaiSanPham, columns);
    }

    private void setTextField() {
        DesignHelper.addPlaceHolderTextField(txtMaLoai, "Mã loại");
        DesignHelper.addPlaceHolderTextField(txtTenLoai, "Tên loại");
        DesignHelper.addPlaceHolderTextField(txtGhiChu, "Ghi chú");
    }

    private void setPlaceholderForSetForm() {
        DesignHelper.deletePlaceHolderTextField(txtMaLoai);
        Font font = txtMaLoai.getFont();
        font = font.deriveFont(Font.BOLD);
        txtMaLoai.setFont(font);
        DesignHelper.deletePlaceHolderTextField(txtTenLoai);
        DesignHelper.deletePlaceHolderTextField(txtGhiChu);
    }

    private void clearForm() {
        LoaiHang nv = new LoaiHang();
        tblLoaiSanPham.clearSelection();

        this.setForm(nv);
        this.setTextField();
        this.row = -1;
        this.updateStatus();
        resetBorder();
    }

    private LoaiHang getForm() {
        LoaiHang lh = new LoaiHang();

        lh.setMaLoai(txtMaLoai.getText());
        lh.setTenLoai(txtTenLoai.getText());
        lh.setGhiChu(txtGhiChu.getText());
        return lh;
    }

    private void setForm(LoaiHang lh) {
        resetBorder();
        txtMaLoai.setText(lh.getMaLoai());
        txtTenLoai.setText(lh.getTenLoai());
        txtGhiChu.setText(lh.getGhiChu());
    }

    private void edit() {
        String maLoai = (String) tblLoaiSanPham.getValueAt(row, 0);
        LoaiHang lh = dao.selectById(maLoai);
        this.setPlaceholderForSetForm();
        this.setForm(lh);
        this.updateStatus();
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblLoaiSanPham.getRowCount() - 1);

        // trạng thái form
        txtMaLoai.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnXoa.setEnabled(edit);
        btnSua.setEnabled(edit);

        // điều khiển
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);

        // nút trạng thái
        DesignHelper.setButtonBackgroundColor(btnThem, new Color(51, 255, 0), new Color(102, 255, 102));
        DesignHelper.setButtonBackgroundColor(btnXoa, new Color(255, 0, 0), new Color(255, 102, 102));
        DesignHelper.setButtonBackgroundColor(btnSua, new Color(255, 255, 0), new Color(255, 255, 153));

        // nút điều khiển
        DesignHelper.setButtonBackgroundColor(new Color(153, 204, 255), new Color(204, 255, 255),
                btnFirst, btnPrev, btnNext, btnLast);
    }

    private void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblLoaiSanPham.getModel();
        model.setRowCount(0);
        try {
            List<LoaiHang> list = dao.selectAll();
            for (LoaiHang lh : list) {
                model.addRow(new Object[]{
                    lh.getMaLoai(),
                    lh.getTenLoai(),
                    lh.getGhiChu()
                });
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    private void insert() {
        if (validates() == false) {
            return;
        }
        if (ValidationHelper.isNotDuplicatedID(this, txtMaLoai, "Mã loại",
                dao.selectById(txtMaLoai.getText())) == false) {
            return;
        }
        LoaiHang lh = getForm();
        try {
            dao.insert(lh);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "Thêm thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm không thành công!");
        }
    }

    private void delete() {
        if (true) {
//            String manv = txtMaNV.getText();
            if (MsgBox.confirm(this, "Bạn có muốn xóa hay không?")) {
                try {
                    String maLoai = txtMaLoai.getText();
                    dao.delete(maLoai);
                    this.fillTable();
                    this.clearForm();
                    JOptionPane.showMessageDialog(this, "Xoá thành công");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Xoá không thành công");
                }
            }
        }
    }

    private void update() {
        if(validates()==false){
            return;
        }
        LoaiHang lh = getForm();
        try {
            dao.update(lh);
            this.fillTable();
            MsgBox.alert(this, "Cập nhật thành công!");

        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật không thành công!");
        }
    }

    private void first() {
        row = 0;
        edit();
    }

    private void prev() {
        if (row > 0) {
            row--;
            edit();
        }
    }

    private void next() {
        if (row < tblLoaiSanPham.getRowCount() - 1) {
            row++;
            edit();
        }
    }

    private void last() {
        row = tblLoaiSanPham.getRowCount() - 1;
        edit();
    }

    private void resetBorder() {
        ValidationHelper.resetBorderColor(txtMaLoai, txtTenLoai, txtGhiChu);
    }

    private boolean validates() {

        if (ValidationHelper.isValidLength(this, txtMaLoai, "Mã loại", 7) == false) {
            return false;
        }
        if (ValidationHelper.isValidLength(this, txtTenLoai, "Tên loại", 255) == false) {
            return false;
        }
        if (ValidationHelper.isValidLengthNullableField(this, txtGhiChu, "Ghi chú", 255) == false) {
            return false;
        }
        return true;
    }

}
