/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Sell.UI;

import com.Sell.DAO.HinhAnhDao;
import com.Sell.DAO.LoaiHangDAO;
import com.Sell.DAO.SanPhamDAO;
import com.Sell.Helper.DesignHelper;
import com.Sell.entity.HinhAnh;
import com.Sell.entity.SanPham;
import com.Sell.Helper.ImageHelper;
import com.Sell.Helper.MsgBox;
import com.Sell.entity.LoaiHang;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trongtai
 */
public class QL_SanPham extends javax.swing.JPanel {

    SanPhamDAO spDAO = new SanPhamDAO();
    int row = -1;
    List<HinhAnh> listHinhAnh = new ArrayList<>();
    List<HinhAnh> listHinhAnhThem = new ArrayList<>();
    List<HinhAnh> listHinhAnhXoa = new ArrayList<>();
    HinhAnhDao haDAO = new HinhAnhDao();

    /**
     * Creates new form CuaHangJPanel
     */
    public QL_SanPham() {
        initComponents();
        init();
        initLoaiHang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitle = new com.k33ptoo.components.KGradientPanel();
        jLabel6 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        panelContents = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelSanPham = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnLoaiSanPham = new javax.swing.JButton();
        panelInput = new javax.swing.JPanel();
        txtMaSanPham = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtNhaSX = new javax.swing.JTextField();
        cboLoaiHang = new javax.swing.JComboBox<>();
        txtGiaTien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        panelFunction = new javax.swing.JPanel();
        btnMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        panelDieuKhien = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jListHinhAnh = new javax.swing.JList<>();
        btnThemHinhAnh = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        lblHinhAnh = new javax.swing.JLabel();
        btnXoaHinhAnh = new javax.swing.JButton();
        cboLoaiSP = new javax.swing.JComboBox<>();
        panelLoaiSanPham = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        panelInput1 = new javax.swing.JPanel();
        txtMaLoai = new javax.swing.JTextField();
        txtTenLoai = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu1 = new javax.swing.JTextArea();
        panelFunction1 = new javax.swing.JPanel();
        btnMoi1 = new javax.swing.JButton();
        btnThem1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        panelDieuKhien1 = new javax.swing.JPanel();
        btnFirst1 = new javax.swing.JButton();
        btnPrev1 = new javax.swing.JButton();
        btnNext1 = new javax.swing.JButton();
        btnLast1 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblLoaiSanPham = new javax.swing.JTable();
        btnSanPham = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1010, 619));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());

        panelTitle.setkBorderRadius(0);
        panelTitle.setkEndColor(new java.awt.Color(102, 216, 211));
        panelTitle.setkGradientFocus(1000);
        panelTitle.setkStartColor(new java.awt.Color(0, 185, 215));
        panelTitle.setPreferredSize(new java.awt.Dimension(1150, 50));
        panelTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSanPhamMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("TRANG CHỦ/ QUẢN LÝ CỬA HÀNG");
        jLabel6.setPreferredSize(new java.awt.Dimension(210, 50));

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(804, Short.MAX_VALUE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        add(panelTitle, java.awt.BorderLayout.NORTH);

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setPreferredSize(new java.awt.Dimension(1010, 540));
        panelContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSanPhamMouseClicked(evt);
            }
        });
        panelContent.setLayout(new java.awt.CardLayout());

        panelContents.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(335, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ SẢN PHẨM");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSanPhamMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        panelContents.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.CardLayout());

        panelSanPham.setPreferredSize(new java.awt.Dimension(1050, 509));
        panelSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSanPhamMouseClicked(evt);
            }
        });

        jPanel6.setPreferredSize(new java.awt.Dimension(1020, 499));

        jPanel7.setPreferredSize(new java.awt.Dimension(1010, 475));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSanPhamMouseClicked(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLoaiSanPham.setBackground(new java.awt.Color(255, 153, 0));
        btnLoaiSanPham.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLoaiSanPham.setText("LOẠI SẢN PHẨM");
        btnLoaiSanPham.setPreferredSize(new java.awt.Dimension(150, 40));
        btnLoaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiSanPhamActionPerformed(evt);
            }
        });
        jPanel7.add(btnLoaiSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, -1, -1));

        txtMaSanPham.setPreferredSize(new java.awt.Dimension(80, 35));
        txtMaSanPham.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaSanPhamFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaSanPhamFocusLost(evt);
            }
        });

        txtTenSP.setPreferredSize(new java.awt.Dimension(80, 35));
        txtTenSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenSPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenSPFocusLost(evt);
            }
        });

        txtNhaSX.setPreferredSize(new java.awt.Dimension(80, 35));
        txtNhaSX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNhaSXFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNhaSXFocusLost(evt);
            }
        });

        cboLoaiHang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiHang.setPreferredSize(new java.awt.Dimension(64, 35));

        txtGiaTien.setPreferredSize(new java.awt.Dimension(80, 35));
        txtGiaTien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGiaTienFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGiaTienFocusLost(evt);
            }
        });

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        txtGhiChu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGhiChuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGhiChuFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txtGhiChu);

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtGiaTien, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addComponent(txtNhaSX, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTenSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMaSanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboLoaiHang, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addComponent(cboLoaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(txtNhaSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.add(panelInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 320));

        btnMoi.setBackground(new java.awt.Color(51, 255, 255));
        btnMoi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/refresh-icon.png"))); // NOI18N
        btnMoi.setText(" MỚI");
        btnMoi.setPreferredSize(new java.awt.Dimension(120, 30));
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(51, 255, 0));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/Add.png"))); // NOI18N
        btnThem.setText(" THÊM");
        btnThem.setPreferredSize(new java.awt.Dimension(120, 30));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(255, 0, 0));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/Delete.png"))); // NOI18N
        btnXoa.setText(" XÓA");
        btnXoa.setPreferredSize(new java.awt.Dimension(120, 30));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(255, 255, 0));
        btnSua.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/UPDATE.png"))); // NOI18N
        btnSua.setText(" SỬA");
        btnSua.setPreferredSize(new java.awt.Dimension(120, 30));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFunctionLayout = new javax.swing.GroupLayout(panelFunction);
        panelFunction.setLayout(panelFunctionLayout);
        panelFunctionLayout.setHorizontalGroup(
            panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFunctionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFunctionLayout.createSequentialGroup()
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFunctionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFunctionLayout.setVerticalGroup(
            panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFunctionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFunctionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel7.add(panelFunction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 325, 270, 100));

        btnFirst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFirst.setText("|<");
        btnFirst.setPreferredSize(new java.awt.Dimension(100, 25));
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrev.setText("<<");
        btnPrev.setPreferredSize(new java.awt.Dimension(100, 25));
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext.setText(">>");
        btnNext.setPreferredSize(new java.awt.Dimension(100, 25));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLast.setText(">|");
        btnLast.setPreferredSize(new java.awt.Dimension(100, 25));
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDieuKhienLayout = new javax.swing.GroupLayout(panelDieuKhien);
        panelDieuKhien.setLayout(panelDieuKhienLayout);
        panelDieuKhienLayout.setHorizontalGroup(
            panelDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDieuKhienLayout.createSequentialGroup()
                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDieuKhienLayout.setVerticalGroup(
            panelDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDieuKhienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel7.add(panelDieuKhien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 432, -1, -1));

        jListHinhAnh.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListHinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListHinhAnhMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jListHinhAnh);

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 230, 70));

        btnThemHinhAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/btnThemHinhAnh_icons8_add_16px_2.png"))); // NOI18N
        btnThemHinhAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemHinhAnhActionPerformed(evt);
            }
        });
        jPanel7.add(btnThemHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 30, -1));

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSanPham);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 490, 400));

        lblHinhAnh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHinhAnh.setToolTipText("");
        lblHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jPanel7.add(lblHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 190, 240));

        btnXoaHinhAnh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/btnXoaHinhAnh_icons8_delete_16px.png"))); // NOI18N
        btnXoaHinhAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaHinhAnhActionPerformed(evt);
            }
        });
        jPanel7.add(btnXoaHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 30, -1));

        cboLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboLoaiSPMouseClicked(evt);
            }
        });
        cboLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiSPActionPerformed(evt);
            }
        });
        jPanel7.add(cboLoaiSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 240, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        panelSanPham.add(jPanel6);

        jPanel4.add(panelSanPham, "card2");

        jPanel9.setPreferredSize(new java.awt.Dimension(1000, 499));

        jPanel10.setPreferredSize(new java.awt.Dimension(1000, 475));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10jPanel5MouseClicked(evt);
            }
        });

        txtMaLoai.setPreferredSize(new java.awt.Dimension(80, 35));
        txtMaLoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaLoaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaLoaiFocusLost(evt);
            }
        });

        txtTenLoai.setPreferredSize(new java.awt.Dimension(80, 35));
        txtTenLoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenLoaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenLoaiFocusLost(evt);
            }
        });

        txtGhiChu1.setColumns(20);
        txtGhiChu1.setRows(5);
        txtGhiChu1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGhiChu1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGhiChu1FocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(txtGhiChu1);

        javax.swing.GroupLayout panelInput1Layout = new javax.swing.GroupLayout(panelInput1);
        panelInput1.setLayout(panelInput1Layout);
        panelInput1Layout.setHorizontalGroup(
            panelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInput1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTenLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        panelInput1Layout.setVerticalGroup(
            panelInput1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInput1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMoi1.setBackground(new java.awt.Color(51, 255, 255));
        btnMoi1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMoi1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/refresh-icon.png"))); // NOI18N
        btnMoi1.setText(" MỚI");
        btnMoi1.setPreferredSize(new java.awt.Dimension(150, 40));
        btnMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoi1ActionPerformed(evt);
            }
        });

        btnThem1.setBackground(new java.awt.Color(51, 255, 0));
        btnThem1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/Add.png"))); // NOI18N
        btnThem1.setText(" THÊM");
        btnThem1.setPreferredSize(new java.awt.Dimension(150, 40));
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnXoa1.setBackground(new java.awt.Color(255, 0, 0));
        btnXoa1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/Delete.png"))); // NOI18N
        btnXoa1.setText(" XÓA");
        btnXoa1.setPreferredSize(new java.awt.Dimension(150, 40));
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnSua1.setBackground(new java.awt.Color(255, 255, 0));
        btnSua1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSua1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Sell/icons/UPDATE.png"))); // NOI18N
        btnSua1.setText(" SỬA");
        btnSua1.setPreferredSize(new java.awt.Dimension(150, 40));
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFunction1Layout = new javax.swing.GroupLayout(panelFunction1);
        panelFunction1.setLayout(panelFunction1Layout);
        panelFunction1Layout.setHorizontalGroup(
            panelFunction1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFunction1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFunction1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFunction1Layout.createSequentialGroup()
                        .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFunction1Layout.createSequentialGroup()
                        .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelFunction1Layout.setVerticalGroup(
            panelFunction1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFunction1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFunction1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelFunction1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMoi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnFirst1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFirst1.setText("|<");
        btnFirst1.setPreferredSize(new java.awt.Dimension(100, 40));
        btnFirst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirst1ActionPerformed(evt);
            }
        });

        btnPrev1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrev1.setText("<<");
        btnPrev1.setPreferredSize(new java.awt.Dimension(100, 40));
        btnPrev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrev1ActionPerformed(evt);
            }
        });

        btnNext1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNext1.setText(">>");
        btnNext1.setPreferredSize(new java.awt.Dimension(100, 40));
        btnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNext1ActionPerformed(evt);
            }
        });

        btnLast1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLast1.setText(">|");
        btnLast1.setPreferredSize(new java.awt.Dimension(100, 40));
        btnLast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLast1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDieuKhien1Layout = new javax.swing.GroupLayout(panelDieuKhien1);
        panelDieuKhien1.setLayout(panelDieuKhien1Layout);
        panelDieuKhien1Layout.setHorizontalGroup(
            panelDieuKhien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDieuKhien1Layout.createSequentialGroup()
                .addComponent(btnFirst1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrev1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLast1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDieuKhien1Layout.setVerticalGroup(
            panelDieuKhien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDieuKhien1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnFirst1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrev1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnNext1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnLast1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tblLoaiSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaiSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiSanPhamMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblLoaiSanPham);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnSanPham.setBackground(new java.awt.Color(255, 153, 0));
        btnSanPham.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSanPham.setText("SẢN PHẨM");
        btnSanPham.setPreferredSize(new java.awt.Dimension(150, 40));
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelInput1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFunction1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDieuKhien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(panelInput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelFunction1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelDieuKhien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        panelLoaiSanPham.add(jPanel9);

        jPanel4.add(panelLoaiSanPham, "card3");

        panelContents.add(jPanel4, java.awt.BorderLayout.CENTER);

        panelContent.add(panelContents, "card2");

        add(panelContent, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        this.requestFocusInWindow();
    }//GEN-LAST:event_formFocusGained

    private void panelSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSanPhamMouseClicked
        JComponent component = (JComponent) evt.getSource();
        component.requestFocus();
    }//GEN-LAST:event_panelSanPhamMouseClicked

    private void txtMaLoaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaLoaiFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLoaiFocusGained

    private void txtMaLoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaLoaiFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaLoaiFocusLost

    private void txtTenLoaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenLoaiFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLoaiFocusGained

    private void txtTenLoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenLoaiFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLoaiFocusLost

    private void txtGhiChu1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGhiChu1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChu1FocusGained

    private void txtGhiChu1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGhiChu1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChu1FocusLost

    private void btnMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoi1ActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed

    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnFirst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirst1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFirst1ActionPerformed

    private void btnPrev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrev1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrev1ActionPerformed

    private void btnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNext1ActionPerformed

    private void btnLast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLast1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLast1ActionPerformed

    private void tblLoaiSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiSanPhamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblLoaiSanPhamMouseClicked

    private void jPanel10jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10jPanel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10jPanel5MouseClicked

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        panelSanPham.setVisible(true);
        panelLoaiSanPham.setVisible(false);
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        edit();
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void btnThemHinhAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemHinhAnhActionPerformed
        addImageToList();
    }//GEN-LAST:event_btnThemHinhAnhActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        DesignHelper.last(row, tblSanPham);
        this.edit();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        DesignHelper.next(row, tblSanPham);
        this.edit();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        DesignHelper.prev(row);
        this.edit();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        DesignHelper.first(row);
        this.edit();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void txtGhiChuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGhiChuFocusLost
        if (txtGhiChu.getText().trim().length() == 0) {
            txtGhiChu.setText("Ghi chú");
            DesignHelper.addPlaceHolderTextField(txtGhiChu);
        }
    }//GEN-LAST:event_txtGhiChuFocusLost

    private void txtGhiChuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGhiChuFocusGained
        if (txtGhiChu.getText().equals("Ghi chú")) {
            txtGhiChu.setText("");
            DesignHelper.deletePlaceHolderTextField(txtGhiChu);
        }
    }//GEN-LAST:event_txtGhiChuFocusGained

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void txtGiaTienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGiaTienFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTienFocusLost

    private void txtGiaTienFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGiaTienFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaTienFocusGained

    private void txtNhaSXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNhaSXFocusLost

        if (txtNhaSX.getText().trim().length() == 0) {
            DesignHelper.addPlaceHolderTextField(txtNhaSX, "Nhà sản xuất");
        }
    }//GEN-LAST:event_txtNhaSXFocusLost

    private void txtNhaSXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNhaSXFocusGained
        if (txtNhaSX.getText().equals("Nhà sản xuất")) {
            txtNhaSX.setText("");
            DesignHelper.deletePlaceHolderTextField(txtNhaSX);
        }
    }//GEN-LAST:event_txtNhaSXFocusGained

    private void txtTenSPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenSPFocusLost
        if (txtTenSP.getText().trim().length() == 0) {
            txtTenSP.setText("Tên sản phẩm");
            DesignHelper.addPlaceHolderTextField(txtTenSP);
        }
    }//GEN-LAST:event_txtTenSPFocusLost

    private void txtTenSPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenSPFocusGained
        if (txtTenSP.getText().equals("Tên sản phẩm")) {
            DesignHelper.deletePlaceHolderTextField(txtTenSP);
        }
    }//GEN-LAST:event_txtTenSPFocusGained

    private void txtMaSanPhamFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaSanPhamFocusLost
        if (txtMaSanPham.getText().trim().length() == 0) {
            DesignHelper.addPlaceHolderTextField(txtMaSanPham, "Mã sản phẩm");
        }
    }//GEN-LAST:event_txtMaSanPhamFocusLost

    private void txtMaSanPhamFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaSanPhamFocusGained
        if (txtMaSanPham.getText().equals("Mã sản phẩm")) {
            DesignHelper.deletePlaceHolderTextField(txtMaSanPham);
        }
    }//GEN-LAST:event_txtMaSanPhamFocusGained

    private void btnLoaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiSanPhamActionPerformed
        // TODO add your handling code here:
        panelLoaiSanPham.setVisible(true);
        panelSanPham.setVisible(false);
    }//GEN-LAST:event_btnLoaiSanPhamActionPerformed

    private void jListHinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListHinhAnhMouseClicked
        System.out.println(jListHinhAnh.getSelectedIndex());
        hienHinhAnh();
    }//GEN-LAST:event_jListHinhAnhMouseClicked

    private void btnXoaHinhAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaHinhAnhActionPerformed
        xoaHinhAnh();
    }//GEN-LAST:event_btnXoaHinhAnhActionPerformed

    private void cboLoaiSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboLoaiSPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiSPMouseClicked

    private void cboLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiSPActionPerformed
        // TODO add your handling code here:
        fillToTableSanPham();
    }//GEN-LAST:event_cboLoaiSPActionPerformed

    public static void main(String[] args) {
        new QL_SanPham().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnFirst1;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnLast1;
    private javax.swing.JButton btnLoaiSanPham;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnMoi1;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNext1;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnPrev1;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThemHinhAnh;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton btnXoaHinhAnh;
    private javax.swing.JComboBox<String> cboLoaiHang;
    private javax.swing.JComboBox<String> cboLoaiSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList<String> jListHinhAnh;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelContents;
    private javax.swing.JPanel panelDieuKhien;
    private javax.swing.JPanel panelDieuKhien1;
    private javax.swing.JPanel panelFunction;
    private javax.swing.JPanel panelFunction1;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelInput1;
    private javax.swing.JPanel panelLoaiSanPham;
    private javax.swing.JPanel panelSanPham;
    private com.k33ptoo.components.KGradientPanel panelTitle;
    private javax.swing.JTable tblLoaiSanPham;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextArea txtGhiChu1;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtMaSanPham;
    private javax.swing.JTextField txtNhaSX;
    private javax.swing.JTextField txtTenLoai;
    private javax.swing.JTextField txtTenSP;
    // End of variables declaration//GEN-END:variables

    private void init() {
        setTable();
        fillTable();
        fillCombobox();
        fillComboboxLoaiSP();
        fillToTableSanPham();
        clearForm();
        setTextField();
        jListHinhAnh.removeAll();
    }

    private void setTextField() {
        DesignHelper.addPlaceHolderTextField(txtMaSanPham, "Mã sản phẩm");
        DesignHelper.addPlaceHolderTextField(txtTenSP, "Tên sản phẩm");
        DesignHelper.addPlaceHolderTextField(txtNhaSX, "Nhà sản xuất");
        DesignHelper.addPlaceHolderTextField(txtGhiChu, "Ghi chú");
    }

    private void setPlaceHolderForSetForm() {
        DesignHelper.deletePlaceHolderTextField(txtMaSanPham);
        Font font = txtMaSanPham.getFont();
        font = font.deriveFont(Font.BOLD);
        txtMaSanPham.setFont(font);
        DesignHelper.deletePlaceHolderTextField(txtTenSP);
        DesignHelper.deletePlaceHolderTextField(txtNhaSX);
        DesignHelper.deletePlaceHolderTextField(txtGhiChu);
    }

    private void setTable() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("MÃ SP");
        model.addColumn("TÊN SP");
        model.addColumn("NHÀ SX");
        model.addColumn("GIÁ TIỀN");

        tblSanPham.setModel(model);
        DesignHelper.setTable(tblSanPham);
    }

    private void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);
        try {
            List<SanPham> list = spDAO.selectAll();
            for (SanPham sp : list) {
                if (!sp.getMaSanPham().equals("(Mã SP)")) {
                    model.addRow(new Object[]{
                        sp.getMaSanPham(),
                        sp.getTenSP(),
                        sp.getNhaSX(),
                        sp.getGiaTien()

                    });
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    void fillCombobox() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiHang.getModel();

        model.removeAllElements();
        List<LoaiHang> list = lhDao.selectAll();
        model.addElement(new LoaiHang("Tất cả", "Loại Hàng ", "cửa hàng"));
        for (LoaiHang lh : list) {
            model.addElement(lh);
        }
    }

    private SanPham getForm() {
        SanPham sp = new SanPham();
        LoaiHang lh = (LoaiHang) cboLoaiHang.getSelectedItem();

        sp.setMaSanPham(txtMaSanPham.getText());
        sp.setTenSP(txtTenSP.getText());
        sp.setNhaSX(txtNhaSX.getText());
        sp.setGhiChu(txtGhiChu.getText());
        sp.setMaLoai(lh.getMaLoai());
        sp.setGiaTien(Float.parseFloat(txtGiaTien.getText()));
        return sp;
    }

    private void setForm(SanPham sp) {
        txtMaSanPham.setText(sp.getMaSanPham());
        txtTenSP.setText(sp.getTenSP());
        txtNhaSX.setText(sp.getNhaSX());
        txtGhiChu.setText(sp.getGhiChu());
        LoaiHang lh = lhDao.selectById(sp.getMaLoai());
        if (lh != null) {
            cboLoaiHang.setSelectedItem(lh);
        } else {
            cboLoaiHang.setSelectedIndex(0);
        }
        txtGiaTien.setText(sp.getGiaTien() + "");
    }

    private void edit() {
        this.row = tblSanPham.getSelectedRow();
        // đổ sp lên form
        String maSP = (String) tblSanPham.getValueAt(this.row, 0);
        SanPham sp = spDAO.selectById(maSP);
        this.setPlaceHolderForSetForm();
        this.setForm(sp);

        // đổ hình ảnh lên form
        editHinhAnh(maSP);

        this.updateStatus();
    }

    private void editHinhAnh(String maSP) {
        listHinhAnhThem.removeAll(listHinhAnhThem);
        listHinhAnhXoa.removeAll(listHinhAnhXoa);
        listHinhAnh.removeAll(listHinhAnh);
        listHinhAnh = haDAO.selectAllById(maSP);
        if (!listHinhAnh.isEmpty()) {
            lblHinhAnh.setIcon(ImageHelper.revertFromArrayByte(lblHinhAnh, listHinhAnh.get(0).getHinhAnh()));
            jListHinhAnh.setSelectedIndex(1);
        } else {
            DefaultListModel listModel = (DefaultListModel) jListHinhAnh.getModel();
            listModel.removeAllElements();
            jListHinhAnh.setSelectedIndex(-1);
            ImageHelper.setDefaultImage(lblHinhAnh);
        }
        fillElementToJListHinhAnh();
    }

    private void fillElementToJListHinhAnh() {
        if (!listHinhAnh.isEmpty()) {
            DefaultListModel listModel = new DefaultListModel();
            listModel.removeAllElements();
            for (HinhAnh ha : listHinhAnh) {
                listModel.addElement(ha);
            }
            jListHinhAnh.setModel(listModel);
        } else {
            ImageHelper.setDefaultImage(lblHinhAnh);
        }
    }

    void insert() {
        try {
            // Thêm sản phẩm vào db
            SanPham sp = getForm();
            spDAO.insert(sp);
            this.fillTable();

            // Thêm hình ảnh vào db
            if (!listHinhAnhThem.isEmpty()) {
                for (HinhAnh ha : listHinhAnhThem) {
                    ha.setMaSanPham(sp.getMaSanPham());
                    haDAO.insert(ha);
                }
            }

            MsgBox.alert(this, "Thêm sản phẩm thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm sản phẩm thất bại");
        }
    }

    void update() {
        try {
            // Sửa sản phẩm vào db
            SanPham sp = getForm();
            spDAO.update(sp);
            this.fillTable();

            // Thêm hình ở danh sách hình mới listHinhAnhThem
            if (!listHinhAnhThem.isEmpty()) {
                for (HinhAnh ha : listHinhAnhThem) {
                    ha.setMaSanPham(sp.getMaSanPham());
                    haDAO.insert(ha);
                }
            }
            // Xoá hình ở danh sách hình cần xoá listHinhAnhXoa
            if (!listHinhAnhXoa.isEmpty()) {
                for (HinhAnh ha : listHinhAnhXoa) {
                    ha.setMaSanPham(sp.getMaSanPham());
                    haDAO.delete(ha);
                }
            }

            MsgBox.alert(this, "Sửa sản phẩm thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Sửa sản phẩm thất bại");
        }
    }

    void delete() {
        try {
            String maSP = txtMaSanPham.getText();
            // xoá SP trong db
            spDAO.delete(maSP);
            // xoá ha trong db
            haDAO.deleteAllByID(maSP);
            this.fillTable();

            MsgBox.alert(this, "Xoá sản phẩm thành công");
        } catch (Exception e) {
            MsgBox.alert(this, "Xoá sản phẩm thất bại");
        }
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblSanPham.getRowCount() - 1);

        // trạng thái form
        txtMaSanPham.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnXoa.setEnabled(edit);
        btnSua.setEnabled(edit);

        // điều khiển
        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);

        // nút trạng thái
        DesignHelper.setButtonBackgroundColor(btnThem, new Color(51, 255, 0), new Color(102, 255, 102));
        DesignHelper.setButtonBackgroundColor(btnXoa, new Color(255, 0, 0), new Color(255, 102, 102));
        DesignHelper.setButtonBackgroundColor(btnSua, new Color(255, 255, 0), new Color(255, 255, 153));

        // nút điều khiển
        DesignHelper.setButtonBackgroundColor(new Color(153, 204, 255), new Color(204, 255, 255),
                btnFirst, btnPrev, btnNext, btnLast);
    }

    private void clearForm() {
        this.row = -1;
        SanPham sp = new SanPham();
        setForm(sp);
        setTextField();
        updateStatus();

        listHinhAnh.removeAll(listHinhAnh);
        listHinhAnhThem.removeAll(listHinhAnhThem);
        listHinhAnhXoa.removeAll(listHinhAnhXoa);
        ImageHelper.setDefaultImage(lblHinhAnh);
    }

    private void addImageToList() {
        JFileChooser chooser = new JFileChooser("src\\com\\SELL\\Images");
        chooser.setMultiSelectionEnabled(true);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "jpg", "jpeg", "png");
        chooser.setFileFilter(filter);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            // Thêm hình ảnh vào listHinhAnh
            File[] files = chooser.getSelectedFiles();
            for (File file : files) {
                HinhAnh hinhAnh = new HinhAnh();
//                    hinhAnh.setMaSanPham(txtMaSanPham.getText()); // chưa biết Mã sản phẩm
                String tempImagePath = file.getAbsolutePath();
                hinhAnh.setHinhAnh(ImageHelper.convertToByteArray(tempImagePath));

                hinhAnh.setTenHinhAnh(file.getName());
                listHinhAnhThem.add(hinhAnh);
                listHinhAnh.add(hinhAnh);
            }
            fillElementToJListHinhAnh();
            // hiển thị hình ảnh lên lblHinhAnh
            lblHinhAnh.setIcon(ImageHelper.revertFromArrayByte(lblHinhAnh,
                    listHinhAnh.get(listHinhAnh.size() - 1).getHinhAnh()));
            jListHinhAnh.setSelectedIndex(listHinhAnh.size() - 1);
        }
    }

    private void hienHinhAnh() {
        if (jListHinhAnh.getSelectedIndex() < 0) {
            return;
        }
        lblHinhAnh.setIcon(ImageHelper.revertFromArrayByte(lblHinhAnh,
                listHinhAnh.get(jListHinhAnh.getSelectedIndex()).getHinhAnh()));
    }

    private void xoaHinhAnh() {
        int selectedIndex = jListHinhAnh.getSelectedIndex();
        if (selectedIndex < 0) {
            return;
        }
        // thêm objectHinhAnh vào danh sách cần xoá
        listHinhAnhXoa.add(listHinhAnh.get(selectedIndex));

        // xoá object HinhAnh đã được chọn trong danh sách mảng
        listHinhAnh.remove(selectedIndex);
        fillElementToJListHinhAnh();

        // nếu danh sách vẫn còn HinhAnh hiển thị hình ảnh đầu tiên lên sau khi xoá
        if (!listHinhAnh.isEmpty()) {
            lblHinhAnh.setIcon(ImageHelper.revertFromArrayByte(lblHinhAnh,
                    listHinhAnh.get(0).getHinhAnh()));
            jListHinhAnh.setSelectedIndex(0);
        } else {
            ImageHelper.setDefaultImage(lblHinhAnh);
        }
    }

    /* Form loại hàng của Chinh */
    LoaiHangDAO lhDao = new LoaiHangDAO();
    int rowLH = -1;

    private void initLoaiHang() {
        setTableLoaiHang();
        fillTableLoaiHang();
    }

    void setTableLoaiHang() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("MÃ LOẠI");
        model.addColumn("TÊN LOẠI");
        model.addColumn("GHI CHÚ");

        tblLoaiSanPham.setModel(model);
        DesignHelper.setTable(tblLoaiSanPham);
    }

    void fillTableLoaiHang() {
        DefaultTableModel model = (DefaultTableModel) tblLoaiSanPham.getModel();
        model.setRowCount(0);
        try {
            List<LoaiHang> list = lhDao.selectAll();
            for (LoaiHang lh : list) {
                if (!lh.getMaLoai().equals("(ML)")) {
                    model.addRow(new Object[]{
                        lh.getMaLoai(),
                        lh.getTenLoai(),
                        lh.getGhiChu()});
                }
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    LoaiHangDAO loaiHangDAO = new LoaiHangDAO();

    void fillComboboxLoaiSP() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiSP.getModel();
        model.removeAllElements();
        List<LoaiHang> list = loaiHangDAO.selectAll();
        model.addElement(new LoaiHang("Tất cả", "Tất cả ", "cửa hàng"));
        for (LoaiHang cd : list) {
            model.addElement(cd);
        }
    }
    SanPhamDAO spdao = new SanPhamDAO();

    void fillToTableSanPham() {
        DefaultTableModel model = (DefaultTableModel) tblSanPham.getModel();
        model.setRowCount(0);

        try {
            if (cboLoaiSP.getSelectedIndex() == 0) {

                List<SanPham> loaiHangALL = spdao.selectByMaLoaiHang("");
                for (SanPham sp : loaiHangALL) {
                    Object[] row = {sp.getMaSanPham(), sp.getTenSP(), sp.getNhaSX(), sp.getGiaTien(), sp.getGhiChu()};
                    model.addRow(row);
                }
            } else {

                LoaiHang loaiHang = (LoaiHang) cboLoaiSP.getSelectedItem();

                if (loaiHang != null) {

                    List<SanPham> list = spdao.selectByMaLoaiHang(loaiHang.getMaLoai());
                    for (SanPham sp : list) {
                        Object[] row = {sp.getMaSanPham(), sp.getTenSP(), sp.getNhaSX(), sp.getGiaTien(), sp.getGhiChu()};
                        model.addRow(row);
                    }
                }
            }

        } catch (Exception e) {
            // System.out.println("Lỗi nhẹ thôi ko có gì hết! để tb cho vui !");
            e.printStackTrace();

        }

    }

}
