/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Sell.UI;

import com.Sell.DAO.NhanVien_Dao;
import com.Sell.entity.NhanVien;
import com.Sell.Helper.DesignHelper;
import com.Sell.Helper.MsgBox;
//import com.Sell.Helper.PasswordHelper;
import java.awt.Cursor;
import java.util.Properties;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JComponent;

/**
 *
 * @author NguyenTruongChinh
 */
public class QuenMatKhauJDialog extends java.awt.Dialog {

    /**
     * Creates new form QuenMatKhauJDialog
     */
    public QuenMatKhauJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_maNV = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        btn_confirm = new com.k33ptoo.components.KButton();
        btn_cancel = new com.k33ptoo.components.KButton();
        jLabel2 = new javax.swing.JLabel();

        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LẤY LẠI MẬT KHẨU");

        txt_maNV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_maNVFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_maNVFocusLost(evt);
            }
        });

        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });

        btn_confirm.setBorder(null);
        btn_confirm.setText("XÁC NHẬN");
        btn_confirm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_confirm.setkBorderRadius(50);
        btn_confirm.setkEndColor(new java.awt.Color(153, 255, 0));
        btn_confirm.setkHoverEndColor(new java.awt.Color(183, 250, 83));
        btn_confirm.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_confirm.setkHoverStartColor(new java.awt.Color(115, 172, 80));
        btn_confirm.setkStartColor(new java.awt.Color(81, 132, 49));
        btn_confirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_confirmMouseEntered(evt);
            }
        });
        btn_confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmActionPerformed(evt);
            }
        });

        btn_cancel.setBorder(null);
        btn_cancel.setText("HỦY");
        btn_cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cancel.setkBorderRadius(50);
        btn_cancel.setkEndColor(new java.awt.Color(240, 115, 115));
        btn_cancel.setkHoverEndColor(new java.awt.Color(246, 167, 167));
        btn_cancel.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btn_cancel.setkHoverStartColor(new java.awt.Color(245, 103, 103));
        btn_cancel.setkStartColor(new java.awt.Color(237, 57, 57));
        btn_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_confirmMouseEntered(evt);
            }
        });
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mật khẩu sẽ được gửi về email của bạn");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_maNV)
                    .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(75, 75, 75))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 25, Short.MAX_VALUE)
                        .addComponent(btn_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        add(kGradientPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void txt_maNVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_maNVFocusGained
        // TODO add your handling code here:
        if (txt_maNV.getText().equals(" Mã nhân viên")) {
            txt_maNV.setText("");
            txt_maNV.requestFocus();
            DesignHelper.deletePlaceHolderTextField(txt_maNV);
        }
    }//GEN-LAST:event_txt_maNVFocusGained

    private void txt_maNVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_maNVFocusLost
        // TODO add your handling code here:
        if (txt_maNV.getText().length() == 0) {
            txt_maNV.setText(" Mã nhân viên");
            DesignHelper.addPlaceHolderTextField(txt_maNV);
        }
    }//GEN-LAST:event_txt_maNVFocusLost

    private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
        // TODO add your handling code here:
        if (txt_email.getText().equals(" Email")) {
            txt_email.setText("");
            txt_email.requestFocus();
            DesignHelper.deletePlaceHolderTextField(txt_email);
        }
    }//GEN-LAST:event_txt_emailFocusGained

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        // TODO add your handling code here:
        if (txt_email.getText().length() == 0) {
            txt_email.setText(" Email");
            DesignHelper.addPlaceHolderTextField(txt_email);
        }
    }//GEN-LAST:event_txt_emailFocusLost

    private void btn_confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmActionPerformed
        // TODO add your handling code here:
        changePass();
    }//GEN-LAST:event_btn_confirmActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        cancel();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btn_confirmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_confirmMouseEntered
        // TODO add your handling code here:
        JComponent component = (JComponent) (evt.getSource());
        component.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btn_confirmMouseEntered

    private void kGradientPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseClicked
        // TODO add your handling code here:
        JComponent component = (JComponent) evt.getSource();
        component.requestFocusInWindow();
    }//GEN-LAST:event_kGradientPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhauJDialog dialog = new QuenMatKhauJDialog(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btn_cancel;
    private com.k33ptoo.components.KButton btn_confirm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_maNV;
    // End of variables declaration//GEN-END:variables

    void init() {
        setLocationRelativeTo(null);
        style();
    }

    private static final String alpha = "abcdefghijklmnopqrstuvwxyz"; // a-z
    private static final String alphaUpperCase = alpha.toUpperCase(); // A-Z
    private static final String digits = "0123456789"; // 0-9
    private static final String ALPHA_NUMERIC = alpha + alphaUpperCase + digits;

    private static Random rand = new Random();

    void style() {
        txt_maNV.setText(" Mã nhân viên");
        txt_email.setText(" Email");
        DesignHelper.addPlaceHolderTextField(txt_maNV);
        DesignHelper.addPlaceHolderTextField(txt_email);
    }

    public static int randomNumber(int min, int max) {
        return rand.nextInt((max - min) + 1) + min;
    }

    public String randomPassword(int numberOfCharactor) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < numberOfCharactor; i++) {
            int number = randomNumber(0, ALPHA_NUMERIC.length() - 1);
            char ch = ALPHA_NUMERIC.charAt(number);
            sb.append(ch);
        }
        return sb.toString();
    }

    NhanVien_Dao dao = new NhanVien_Dao();

    void changePass() {
        if (validates()) {
            NhanVien nv = getForm();
            try {
                dao.resetPassword(nv);
                try {
                    Properties p = new Properties();
                    p.put("mail.smtp.auth", "true");
                    p.put("mail.smtp.starttls.enable", "true");
                    p.put("mail.smtp.host", "smtp.gmail.com");
                    p.put("mail.smtp.port", 587);

                    final String fromEmail = "chinhnguyen010801@gmail.com";
                    final String password = "mdktkskgkm1";
                    final String toEmail = txt_email.getText();
                    final String subject = "Đặt lại mật khẩu";
                    final String boy = "Mã nhân viên: " + nv.getMaNV() + ". Mật khẩu được đặt lại là: ";
                    final String body = nv.getMatKhau();
                    
                    Session s = Session.getInstance(p,
                            new javax.mail.Authenticator() {
                        protected javax.mail.PasswordAuthentication getPasswordAuthentication() {
                            return new javax.mail.PasswordAuthentication(fromEmail, password);
                        }
                    });

                    MimeMessage msg = new MimeMessage(s);
                    msg.setFrom(new InternetAddress(fromEmail));
                    msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail));
                    msg.setSubject(subject);
                    msg.setText(boy + body);
//                    nv.setMatKhau(PasswordHelper.doHashing(body));
                    Transport.send(msg);
                    MsgBox.alert(this, "Mật khẩu đã gửi về email của bạn!");
                    style();
                } catch (Exception e) {
                    Logger.getLogger(QuenMatKhauJDialog.class.getName()).log(Level.SEVERE, null, e);
                }
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        }
    }

    NhanVien getForm() {
        NhanVien nv = new NhanVien();
        nv.setMaNV(txt_maNV.getText());
        nv.setMatKhau(randomPassword(8));
        return nv;
    }

    void cancel() {
        if (MsgBox.confirm(this, "Bạn có muốn hủy không?")) {
            this.dispose();
        }
    }

    boolean validates() {

        String taiKhoan = txt_maNV.getText();
        String email = new String(txt_email.getText());
        NhanVien nhanVien = dao.selectById(taiKhoan);
        String tb = "";
        if (taiKhoan.equals(" Mã nhân viên")) {
            tb = " Vui lòng nhập mã nhân viên ";

        } else if (nhanVien == null) {
            tb = " Sai mã nhân viên";

        } else if (txt_email.getText().equals(" Email")) {
            tb = " Vui Lòng nhập email";

        } else if (!email.equals(nhanVien.getEmail())) {
            tb = " Sai Email";

        }

        if (tb.length() > 0) {
            MsgBox.alert(this, tb);
            return false;
        }
        return true;

    }

}
